### ISSUE TITLE
FlowType #technicaldebt

### ISSUE THREAD

**Issue by imboogieman** [Lokiedu/libertysoil-site#101]
This is a "technology preview" task. We want to have a bit of flow checking in our codebase, but it doesn't look like we can mark everything with types. yet.

See https://github.com/facebook/flow/issues/1081 for some inspiration regarding component checking
See https://github.com/facebook/immutable-js/issues/203 & https://gist.github.com/bouk/911b8d4993c19de3f98f for type-definitions for immutable-js

**Comment by romagorbunov** [comment]
@dmitryvdovin please, give it ana estimate.

**Comment by voidxnull** [comment]
plus! 0/3

**Comment by indeyets** [comment]
@romangorbunov1 I moved this to the end of the queue. it's not critical and we have more important things to do
