### ISSUE TITLE
(5) Issue 110: "Minor update" checkbox won't publish the new post in follower's news feeds [5]

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#110]
As a user, I want to be able to publish information without flooding my follower's news feeds - to be able to publish more updates without causing bad user experience for everyone who follows me.

**Comment by voidxnull** [comment]
plus! 0/2

**Comment by voidxnull** [comment]
plus! 3.83/1.83 Not ready yet (see Action Plan).

**Comment by voidxnull** [comment]
plus! 1.67/1.67 Now user's own minor updates are shown on the news feed. Checkbox is shown only for posts having the minor update flag set.

**Comment by voidxnull** [comment]
plus! 0.67/0.67 Added simple tooltips.

**Comment by romagorbunov** [comment]
@indeyets  The feature is not seen on the production site, please, revise it. Something might have gone wrong on the deployment step.
