### ISSUE TITLE
(3) Issue 111: Suggest drop-down for hashtags [3]

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#111]
As a user, I want an easy way to use the hashtag that I know is already used on the site - without entering it all manually, so that I can add more hashtags to posts, re-use hashtags more often, avoid creating duplicate hashtags.

**Acceptance criteria:** we want a fast and draft implementation here that could be not optimal in terms of scalability or server load - but would work for us in the next 3-6 months.

**How to demo:** go to hashtag adding/editing interface, enter 2 letters "De", see the drop-down with available suggestions. Suggestions sort order can be any, easiest to implement will do. Selecting the tag from the drop down adds it to the list of selected tags.

**Comment by voidxnull** [comment]
plus! 0/2

**Comment by voidxnull** [comment]
plus! 1.33/-0.67
