### ISSUE TITLE
(8) Issue 112: Related/See also posts on a 1 post page in sidebar

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#112]
As a user, I want to be able to browse posts without going back and forth - to go from one post to another related post, like I do it on YouTube, to make my browsing experience more smooth and streamlined.

**Acceptance criteria:** we need super basic implementation that would not attempt to be too smart in any way. We want to output 3-5 related posts to the right of the post (as in youtube), but the degree/algorithm of relationship does not matter much at this point.

**Comment by voidxnull** [comment]
plus! 0/3

**Comment by voidxnull** [comment]
plus! 0.83/0 Trying out different ways to find related posts.

**Comment by voidxnull** [comment]
plus! 0/3

**Comment by voidxnull** [comment]
plus! 6.33/1.17 Can't get knex working properly yet.

**Comment by voidxnull** [comment]
plus! 2/1.99
