### ISSUE TITLE
(8) Issue 114: Fully automated no-trigger mail digest for every active registered user

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#114]
**User story:** As a user, I am short with time and want to receive best content from LibertySoil.org in my inbox - without a need to re-visit the site too often, so that I can keep track of the best content on the site easier.

**Acceptance criteria:** Mails are sent precisely on triggers and the content is correctly aggregated and displayed in mails.

**N.B.:** More info on mails triggers conditions and content one can find here https://docs.google.com/spreadsheets/d/1qSc2V1MYccpg7_T_HpSMS_Ku92_ORf14OCZEAnpvuUs/edit#gid=0

**Comment by voidxnull** [comment]
plus! 0/5

**Comment by indeyets** [comment]
@romangorbunov1 what time should the mails be sent at? 12PM?

**Comment by indeyets** [comment]
plus!  -2d 2/2

**Comment by romagorbunov** [comment]
plus! @dmitryvdovin 0/-5

**Comment by romagorbunov** [comment]
plus! @romangetman 0/3

**Comment by xekc** [comment]
plus! 0.1/0.1
