### ISSUE TITLE
(0.83/-1.17) (3) Issue 115: Tag cloud - location tags

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#115]
**User story:** As a user I want to see location tags, that were already used on the site, to be able to discover new content and evaluate the project as a library of resources. 

**Acceptance criteria:** The relevant tab must be placed in the right side bar leading to the location tag cloud page, so any user can click on it and go to the page where all tags presented in a cloud view.

**Design:** See the attachments

**Comment by voidxnull** [comment]
plus! 0/2

**Comment by indeyets** [comment]
plus! 0.53/0.53

**Comment by voidxnull** [comment]
plus! 0.83/-1.17

**Comment by guiltypet** [comment]
All Geotags icon is displayed in the left side bar in the breadcrumbs and after clicking on it user is redirected to Geotag cloud page. The same behavior for Hashtag and School tag. Verified on Win7/Chrome 50.
