### ISSUE TITLE
(1) Issue 116: technical clickable breadcrumbs for geo tags in page footer for "Earth -> Europe -> United Kingdom -> London"

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#116]
**User story:** As a site admin or active user, I want to see a full clickable breadcrumbs path in the footer for any location tag page, to be able to evaluate the project as a library of education-focused resources and see what tags need content. 

**Acceptance criteria:** Location tags breadcrumbs are displayed in the footer on all location pages. And the user can navigate using this breadcrumbs.

**Design:** Please, see the mockup attached.

**UX:** Breadcrumbs in the footer plays less for easy user navigation than for SEO purposes.

**Comment by indeyets** [comment]
plus! 0.77/0.77
