### ISSUE TITLE
(5) Issue 117: "Like" for any tag page, news feed entry for liked tag

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#117]
As a user, I want to be able to like the tag (hashtag, school tag, geo tag) to display my support for it's meaning and share it with my followers.

Like "heart" on the tag page has to automatically generate a standard post 
"(userpicture) Username (heart) full tagname" post in user's timeline, both username/userpicture and tagname are linked accordingly. **No other elements are visible in the block.** Design follows the same style, but only those elements are in the block. Height is about 45px.

**Comment by indeyets** [comment]
plus! 0/2

**Comment by indeyets** [comment]
plus! 0.56/0

**Comment by voidxnull** [comment]
plus! 0/4

**Comment by voidxnull** [comment]
plus! 1.17/0

**Comment by voidxnull** [comment]
plus! 4/1.17 Working on tests.

**Comment by voidxnull** [comment]
plus! 3/3 Refactored SET_CURRENT_USER, added tests.

**Comment by voidxnull** [comment]
plus! 3.33/3.33 Added the tag buttons.

**Comment by voidxnull** [comment]
plus! -3/0 https://trello.com/c/Tg3XmdPA/315-issue-134-no-i-follow-after-login

**Comment by voidxnull** [comment]
plus! 2.67/0 Working on the post component.

**Comment by voidxnull** [comment]
plus! 2.5/2.17 Done.

**Comment by indeyets** [comment]
There are no notification about liked tag and unable to like school tag and geo tag

**Comment by indeyets** [comment]
plus! 0.17/0.17

**Comment by voidxnull** [comment]
Just checked it. Works as intended: "like" posts are displayed on the user's feed and on `/user/:username`. Schools and geotags work just fine. Have you applied the migrations: `npm run db:migrate` or `knex migrate:latest`?

**Comment by indeyets** [comment]
plus! 0.85/0.85

**Comment by indeyets** [comment]
plus! 0.04/0.04
