### ISSUE TITLE
(8) Issue 118: Supplement information to location suggestions

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#118]
**User story:** As a user, I want to get specified suggestions for geo tags to let me tag posts with correct location tags.

This is to create better UX and skip incorrect values input in case of homograph.
E.i. There are two Londons, the first is in the United Kingdom, known as the capital of the state, the other is in Canada, Ontario region.

**Acceptance criteria:** The user is suggested with location tags with no ambiguity to choose which is provided by clear information display in suggestion result menu.

**How to demo:** 
I will type Memphis and get two suggestions: 
- Memphis, Egypt 
- Memphis, Tennessee,  USA

I will type Lebanon and get two suggestions: 
- Lebanon
- Lebanon, New Hampshire, USA

I will type Moscow and get two suggestions: 
- Moscow, Russia
- Moscow, Kansas, USA

**UX** Dynamic search with suggestion lists complimented with additional full names or abbreviation commonly used for the locations.

**Comment by indeyets** [comment]
plus! 0.92/0.92

**Comment by voidxnull** [comment]
plus! 0/3

**Comment by voidxnull** [comment]
plus! 0.5/-2.5

**Comment by indeyets** [comment]
I cannot verify it. Now Location tag cannot be added. 
I've created separate card that is associated with this issue https://trello.com/c/WYV2oAS3/407-issue-225-user-is-unable-to-add-school-tag-location-tag-and-hashtag-to-your-post

**Comment by indeyets** [comment]
plus! 0.44/0.44

**Comment by guiltypet** [comment]
The user is suggested with location tags. Have checked different options. Verified on Win 7/Chrome 50/FF45/Opera 35, iPhone 6 /iOS 9.3.1 on both production and alpha servers.
