### ISSUE TITLE
[enh] "via" - liked post visible to all user's followers as a "via @username" post

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#119]
**User story:** As a user, I want my followers to see posts, which I like, appearing in the news feed, so they can read it, like it or interact with it in other possible ways and so I can share content which is interesting to me with my network.

**Acceptance criteria:** When the user likes a post, it immediately appears in his followers news feed.

**How to demo:** Login to libertysoil.org as a user at least with 1 active follower, hit the heart icon on the first post in the news feed, ask any of the follower to take a screenshot of the top of the news feed just after that. 

or

Ask any of the follower to like any post in his news feed, reload the page open at news feed tab and take the screenshot of the top entry in the feed.

**Design:** Please, see the mockup attached.

**UX** The post header must be supplemented with clickable username, so the user can go and see the user profile, followed by the heart icon and additional text.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214154731095139)
┆Created By: Vlad

**Comment by indeyets** [comment]
plus! 1.12/1.12

**Comment by xekc** [comment]
Change of priorities, task cancelled.
