### ISSUE TITLE
(5) Issue 121: Aggregation posts on location tag pages acc. to location hierarchy

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#121]
**User story:** As a user I want to go on a location tag page and see all posts there geographically referred to that location. E.g. I want to see posts tagged with [Portsmouth] on [United Kingdom] page.

**Criteria of acceptance:** All pages of parent or higher level of the locations hierarchy must display posts tagged with child or lower level locations.

**Comment by voidxnull** [comment]
plus! 0/5 We will need to rewrite our geonames importer. The current one doesn't reuse tags that already in the database.

**Comment by voidxnull** [comment]
plus! 2/0

**Comment by voidxnull** [comment]
plus! 2/0

**Comment by voidxnull** [comment]
plus! 1/0
