### ISSUE TITLE
(13) school tag meta data hidden in the open edit page

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#122]
**User story:** As a site admin / active early adopter, I want to add meta information to tags, allow me to input/edit all available fields here and now. 

On this page I expect a full range of input/text area form fields that would allow me to edit all available information about the school tag - and would be able to develop data model around the school entity further (to cover cases such as children hospital or refugee camp - we count all those as schools).

This card is a part of https://trello.com/c/ozCeTfOU/164-school-tag

**Acceptance criteria** The site admin sees "edit button" to access editing page with a list of filed for data input.

**Comment by guiltypet** [comment]
Button 'Edit' is displayed and metadata is available to edit
http://alpha.libertysoil.org/s/Butterflies-India-NGO/edit

NOTE: For hashtag and geotag only description is available to edit.
