### ISSUE TITLE
Automated tests on major functionality (2d part)

### ISSUE THREAD

**Issue by imboogieman** [Lokiedu/libertysoil-site#137]
We need to setup constant surveillance on the site and its key point activities by in-house build automated tests and 3d party monitoring software.

**The aim**: to track the site live availability and productivity and to get alerts once one of the major functionalities or key point graph drops due to technical breakup or overload or any force major issue.

**For test cases details**, please, revise this document https://docs.google.com/spreadsheets/d/1KKFP8VkC0KN1XnCDgP7uTnAK9VWlG1f94Orltqwi_Jk/edit#gid=0

**N.B.** This card is the second part of testing practice setup, and it covers only automated tests for the major functionality. The card for site monitoring tests will be thrown in the future releases.

**Comment by indeyets** [comment]
first half

**Comment by indeyets** [comment]
plus!  -7d 4/8 first half

**Comment by indeyets** [comment]
plus! 4.6/0 done

**Comment by RusAlex** [comment]
plus! 3.4/0 unexpected-express

**Comment by guiltypet** [comment]
Waiting for response https://trello.com/c/caaq2PXV/303-automated-tests-on-major-functionality-1st-part

**Comment by RusAlex** [comment]
answered in slack

**Comment by guiltypet** [comment]
plus! 1.3/1.3

**Comment by guiltypet** [comment]
I have observed it for a few weeks and it looks like that all of the major functionalities are implemented.
