### ISSUE TITLE
(2) Issue 143: [wireframe only] Suggestion of tags to other user's post - specification

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#143]
One LS user suggests missing tags for another LS user's post.

People don't have to follow each other to do the suggestion.

We need:

- Suggestion interface based on existing interfaces with minimal notifications.
- Interface for a user to review and accept/reject suggested tags.

This task does not cover notifications (separate task).

**Comment by indeyets** [comment]
plus! 0.56/0.56

**Comment by indeyets** [comment]
Wireframes updated

**Comment by indeyets** [comment]
Uploaded mobile UI screens:

8 - Mobile post.png — Post with tag suggestion functionality.

9 - Mobile suggest tags.png — “Suggest tags” block expaned. 

10 - Mobile suggest tags.png — Several suggestions selected.

**Comment by indeyets** [comment]
plus! 6/6 Both versions (desktop + mobile

**Comment by indeyets** [comment]
plus! 3/3
