### ISSUE TITLE
Client-side load sequence optimization

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#146]
As a user, I want to be able to start writing a new post after a successful log in or News Feed page open - as soon as possible, so that I don't have to wait until all content on the page loads (sidebar, news feed content).

Currently it will take you at least 10 seconds before you can start writing your post. 

Our target test scenario is:

While logged in, I open http://www.libertysoil.org -> immediately put a cursor into the new post area -> press Cmd+V to paste my post text -> Click Publish = all that within 1-2 seconds. 

Currently it will take MANY seconds to do that, because the new post form only starts working well after all content loaded in successfully (including all embed.ly previews). We need to attempt to change that and make "New post" form functional **as early** as possible.

Additional requirement: Cmd+Enter has to be equivalent to pressing the "Publish" button.

**Comment by indeyets** [comment]
plus! 5/5
