### ISSUE TITLE
(13) Issue 147: pop-up/pop-down card for tags

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#147]
Hover on any tag (location, topic (hashtag), school, event (planned), mention (planned)) or user name has to give me a quick idea on what's inside - without a need to click. 

Typically (facebook, twitter, google) services display a card on mouseover on such entities. 

We need a similar solution. Our main criteria is that implementation has to be cheap. We are working towards fully responsive design - and do not want to debug client side code of this element on mobile devices. Drop downs like this, when buggy, can cover interface elements, used by people - and annoy everyone. 

Ideally, we should find an open source component that is suitable for our needs and is well tested, has good adoption, works well on mobiles (in whatever way).

We will adjust design requirements to fit that ^ criteria.

**Comment by indeyets** [comment]
how this popup/popdown should be implemented. did you mean after typing tag name some suggestion of existing tags will be offered?

**Comment by indeyets** [comment]
plus! 0.04/0.1
