### ISSUE TITLE
naming re-work for hashtags

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#148]
From the chat log: нужно часа 4-6 на переделку хештегов. Там проблема с именованием: location на сервере; hashtag, tag и location на клиенте. Когда каким то образом нужно работать с хештегами, тратится много сил и времени только на то, чтобы все это безобразие осмыслить.
Может и меньше 4 часов, т.к. там grep-ом в основном работать.

**Comment by xekc** [comment]
@indeyets need your involvement and confirmation here. @dmitryvdovin proposed some refactoring work, I'm for it, need your input.

**Comment by indeyets** [comment]
да, конечно. если нужно переделывать — давайте. ставлю на 1 час :)

**Comment by voidxnull** [comment]
plus! 0/4

**Comment by voidxnull** [comment]
plus! 5/1 Done.

**Comment by guiltypet** [comment]
plus! 0.33/0.33

**Comment by guiltypet** [comment]
I would not be able to verify it as this is technical task for developers to follow code convention and best practice.

**Comment by guiltypet** [comment]
@indeyets could you please check it ? I'm not able to verify it so I need your help.
