### ISSUE TITLE
(1) add permanent "ignore" button to the "people to follow" sidebar block

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#156]
As a user, I want to permanently hide a suggested person to follow from the "People to follow" block, so that I can skip/dismiss suggestions about people I'm not interested in following.

We need to add light gray "Ignore" button next to the "Follow" button. Clicking that button hides the suggested person and never shows him on that list of suggestions again.

Afterwards a new suggested user has to appear in the block.

If there are no people left for me to follow (I have followed or ignored all users on the site) - block has to disappear as such (no background or header).

Acceptance criteria: I'm able to go through all users on the site and either follow or ignore them. Animation is fast.

**Comment by indeyets** [comment]
plus! 1.04/1.04

**Comment by Oopscurity** [comment]
@dmitryvdovin Need API in order to:
1. Throw certain user to ignore list.
2. Get users that are not in the list (of course, user should be able to follow them)

**Comment by Oopscurity** [comment]
plus! 0/6

**Comment by Oopscurity** [comment]
plus! 0.28/0

**Comment by Oopscurity** [comment]
plus! 0.19/0

**Comment by voidxnull** [comment]
plus! 0/2 API

**Comment by voidxnull** [comment]
plus! 2.67/0.67 Added API. Use `ignoreUser(username)` to ignore a user. Fixed `userSuggestions` to not to include ignored users. Don't forget to apply the new migration.

**Comment by Oopscurity** [comment]
plus! 1.07/0

**Comment by Oopscurity** [comment]
plus! 0.56/0 debug

**Comment by voidxnull** [comment]
plus! 0.67/0.67 Refactored the `userSuggestions` controller.

**Comment by Oopscurity** [comment]
plus! 0.82/0 Working with block's appearance.

**Comment by Oopscurity** [comment]
plus! 1.08/0 Implemented with fast animation

**Comment by Oopscurity** [comment]
plus! 0/-2

**Comment by Oopscurity** [comment]
plus! 0.6/0.6

**Comment by guiltypet** [comment]
plus! 1.05/1.05

**Comment by guiltypet** [comment]
Done. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35.
"People to follow" block is missing on mobile devices. I will create separate card for that.
