### ISSUE TITLE
"Used recently" tab for Location tags,  Hashtags, School tags.

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#157]
Following work (and design) done in https://trello.com/c/MJMug7tW/201-13-tags-to-a-post-13 we need to append our existing interface with the tab "Used recently".

User needs to be able to effortlessly (and with no danger of losing his draft) add recently used tags of all three kinds to his new or edited post.

Base of the interface remains the same - but instead of having the search field and "add" button. We only see three blocks of information:

**Used recently:** block shows 5 tags of this kind recently used **by this user** only. Hovering each tag outputs "add" button on top of the tag (will provide design a bit later). Clicking anywhere on the tag (not only on the "add" button - anywhere) adds the tag to the "Added:" list below. Nothing else happens here.

**Added:** block shows all tags (of all kinds) that are already added to this webpost. Hovering each tag shows [x] icon. Clicking the icon removes the tag from list. If the tag was in the "Used recently" list - it re-appears on the list. If the tag was not on the "Used recently" list - it just disappears.

**Comment by indeyets** [comment]
> do we have all what it takes on the data layer? who and how will provide the data?

I believe we do. raw data is there. (pseudocode: `group by hashtags_posts.hashtag_id order by posts.fully_published_at`). @dmitryvdovin should be able to do it without serious complications

**Comment by voidxnull** [comment]
@oopscurity 
Take a look at `add-hashtag-form.js`, `add-school-form.js`, `add-geotag-form.js` in `components/add-tag-modal/`.

First of all, wait for https://github.com/Lokiedu/libertysoil-site/pull/153 to be merged. Or branch out from `fix/hashtag-naming`.

1) You might want to create a separate component that holds all the needed state. Take a look at how `AddedTags` is implemented in `components/add-tag-modal.js`. I propose rendering used tags using `TagCloud`. But you will need to add `onClick` prop to `TagCloud` and `Tag` components.

2) You will have to implement or integrate an existing "Tabs" component. We have one in our codebase but it doesn't fit in here. At this point, the "add tag" modals use a placeholder (just layout with styles) instead of real tabs.

Feel free to ask any questions.

**Comment by indeyets** [comment]
plus! 0.4/0.4

**Comment by Oopscurity** [comment]
plus! 0/10

**Comment by Oopscurity** [comment]
plus! 0.18/0

**Comment by Oopscurity** [comment]
@voidxnull 
> branch out from `fix/hashtag-naming`

Do you mean merge with the branch? How can I do it correctly?

**Comment by Oopscurity** [comment]
plus! 0.5/0

**Comment by Oopscurity** [comment]
plus! 1.54/0

**Comment by Oopscurity** [comment]
plus! 0.5/0

**Comment by Oopscurity** [comment]
plus! 1.15/0

**Comment by voidxnull** [comment]
plus! 0.67/0.67 Added `getAvailableUsername` API method.

**Comment by indeyets** [comment]
plus! 1.01/1.01

**Comment by voidxnull** [comment]
plus! 0.6/0 Code review

**Comment by Oopscurity** [comment]
plus! 0.57/0

**Comment by Oopscurity** [comment]
plus! 0.2/0

**Comment by Oopscurity** [comment]
@dmitryvdovin I need to use new API methods in order to access user's recent tags of all three kinds of tags. These methods should be like this: `getRecentHashtags(number)` and `getRecentSchoolTags(number)`

**Comment by voidxnull** [comment]
plus! 1/1.6 @oopscurity Done.

**Comment by voidxnull** [comment]
plus! 0.67/0.67 Fixed the behavior of the API methods.

**Comment by Oopscurity** [comment]
plus! 3.21/0

**Comment by Oopscurity** [comment]
Done for hashtags.

**Comment by Oopscurity** [comment]
plus! 3.29/1.14

**Comment by Oopscurity** [comment]
Need to standardize actions (check, 'convertModelsToTags') with only specific props of tags.

**Comment by Oopscurity** [comment]
plus! 0.65/0.65

**Comment by Oopscurity** [comment]
Done.

**Comment by xekc** [comment]
@ihork I think this is yours now?

**Comment by Oopscurity** [comment]
plus! 0.55/0.55 fixed mix of tags' model and view

**Comment by voidxnull** [comment]
plus! 0.83/0.83 Review and debugging.

**Comment by indeyets** [comment]
plus! 0.73/0.73

**Comment by indeyets** [comment]
I'm not able to verify. "Used recently" tab does not exist for Location tags, Hashtags and School tags.

**Comment by Oopscurity** [comment]
plus! 2.07/2.07

**Comment by Oopscurity** [comment]
plus! 0.5/0.5 Redux implementation

**Comment by Oopscurity** [comment]
plus! 0.43/0.43 Implemented for post edit page

**Comment by Oopscurity** [comment]
plus! 0.19/0.19

**Comment by Oopscurity** [comment]
plus! 0.3/0.3

**Comment by Oopscurity** [comment]
plus! 0/0 Remade redux version

**Comment by guiltypet** [comment]
plus! 1.03/1.03

**Comment by guiltypet** [comment]
plus! 0.61/0.61

**Comment by guiltypet** [comment]
plus! 0.52/0.52

**Comment by guiltypet** [comment]
Done. Verified on the following environments: Windows Pro 7/Chrome 50/FF45/Opera 35, iPhone 6 /iOS 9.3.1, iPad Mini 2/iOS 8.3, Nexus 5/Android 6.0.1, iPhone 5s/iOS 9.0.
