### ISSUE TITLE
(2) Issue 163: No error message appears when try to register with already registered email

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#163]
http://alpha.libertysoil.org/auth
For all devices and browsers

Create a new account. Try to register with the same email which was registered in previous account. Notice that nothing happens after clicking on "Sign up" button and any error message does not appear.

**Comment by indeyets** [comment]
plus! 0.54/0.54

**Comment by xekc** [comment]
@indeyets please take this one. this is a sensitive element and I'd like you to take care of it.

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 0.71/0 Added checkEmailTaken API and field validation

**Comment by Oopscurity** [comment]
plus! 0.13/0 Use head instead of get api method

**Comment by Oopscurity** [comment]
plus! 0/-1.16

**Comment by Oopscurity** [comment]
plus! 0.1/0.1

**Comment by guiltypet** [comment]
plus! 0.34/0.34

**Comment by guiltypet** [comment]
I can still reproduce it on iOS devices. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35, iPhone 6 /iOS 9.1, iPad Mini 2/iOS 8.3

**Comment by xekc** [comment]
@indeyets bugs blocking user registration are all high priority. could we speed this up somehow?

**Comment by Oopscurity** [comment]
@xekc I'll implement there the same validation interface as the new one in the school edit page and the problem'll be fixed. @indeyets What do you think about this?

**Comment by xekc** [comment]
@oopscurity not quite sure what new school edit interface you mean, might be I haven't seen that yet. @indeyets is it the one you work on?

**Comment by Oopscurity** [comment]
@xekc that's it ^

**Comment by Oopscurity** [comment]
Need async validation feature.
The issue in the repo of `react-inform` component, that's used for validation: https://github.com/theadam/react-inform/issues/5

**Comment by Oopscurity** [comment]
Seems like now (using `react-inform` library) there's no way to pass autogenerated username (first name + last name) to the username field.
Created the related issue in the `react-inform` repo: https://github.com/theadam/react-inform/issues/8

**Comment by Oopscurity** [comment]
Most of errors are handled by `react-inform` through its validation interface. See attached screenshot.

**Comment by Oopscurity** [comment]
All problems have been solved.

**Comment by guiltypet** [comment]
"Email is taken" message appears when use already registered email while registration
