### ISSUE TITLE
"Please check this box if you want to proceed" hint does not appear on iOS devices

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#164]
http://alpha.libertysoil.org/auth
iPhone 5 (iOS 8.3), iPhone 5s (iOS 9.0), iPhone 6 (9.1)

Go to registration screen and fill in all field except "I agree to Terms and Condiions" checkbox. Tap on "Sign up" button. Nothing happens and no hint appears.

**Comment by indeyets** [comment]
plus! 0.38/0.38

**Comment by xekc** [comment]
This requires a re-do of error reporting. Right way of error reporting would follow Facebook's example (mobile version) - error hints are displayed at the top of the page, page is scrolled up, error text is descriptive enough for user to understand what's going on. It is a low priority issue that has to be fixed globally for all errors, not only this one.

**Comment by xekc** [comment]
Design is a blocker here.
