### ISSUE TITLE
Tag type helper hover

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#168]
As an early adopter, I want to understand clearly what each icon in new post interface means exactly, to be more comfortable with posting interface.

Each tag type icon has to display short action summary:

- Tag a School
- Add Location
- Tag relevant date
- Mention someone
- Hashtags

**Acceptance criteria:**

1. Smooth, fast animation. Show/hide is no good - we need to animate suggestion in / out - but this animation has to be **very** fast, even on weak devices. I'm open to suggestions.

2. Click anywhere (including action summary text itself) has to open the modal window. 

3. Mobile-friendly. There is no hover on mobiles, single "short tap" has to show it, second tap - open the modal window, "long tap" - open modal window without summary text display. There has to be some industry standard here we could use?

Hover on the icon opens the summary text with animation (slide out left to right?), hover out, after 1 sec delay, closes it (slide in right to left).

**Comment by indeyets** [comment]
plus! 1.09/1.09
