### ISSUE TITLE
(21) Issue 170: Geo tag page redesign: client side code

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#170]
Client side code for geto tag page layout improvements.

**Comment by indeyets** [comment]
plus! 4.94/4.94

**Comment by indeyets** [comment]
plus! 7.12/7.12

**Comment by indeyets** [comment]
All pager redesigned.

**Comment by guiltypet** [comment]
plus! 0.85/0.85

**Comment by guiltypet** [comment]
I've tested it and the layout of Geo/School/Hash tag pages does not look as on original screenshots. 
Checked on Windows Pro 7/Chrome 49/FF45/Opera 35, iPhone 6 /iOS 9.1, iPad Mini 2/iOS 8.3
I also created separate card related to this task
https://trello.com/c/mobHv0hi/452-issue-270-new-button-does-not-work-for-location-hashtag-and-school-tags

**Comment by guiltypet** [comment]
Tag page layout displayed properly. Verified on iPad Mini 2/iOS 8.3, Windows Pro 7/Chrome 50, Motorola Moto X (2nd Gen.)/Android 5.1.1, iPhone 6 /iOS 9.3.1
