### ISSUE TITLE
(0.5) Issue 174: Bug: Liked tag does not appear in user's "My Likes"

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#174]
Currently only liked posts appear in "My Likes".

All liked objects have to appear in this feed.

**Comment by Oopscurity** [comment]
plus! 0/3

**Comment by Oopscurity** [comment]
plus! 0.25/0

**Comment by voidxnull** [comment]
plus! 0.33/0.33 Refactoring APIs and pages.

**Comment by Oopscurity** [comment]
plus! 0.25/0

**Comment by Oopscurity** [comment]
plus! 0.3/0

**Comment by voidxnull** [comment]
plus! 1/1 Done.

**Comment by Oopscurity** [comment]
plus! 1.71/0

**Comment by guiltypet** [comment]
Unable to like hashtags. Internal server error appears after clicking on "Heart" icon. Please see attachment

**Comment by guiltypet** [comment]
"Likes" section does not appear in user's profile for other user if user has liked 1 geo/school/hashtag only. Please see attached video

**Comment by Oopscurity** [comment]
@ihork I can't find this problem in `master` and `stable` branches. See attached video.

**Comment by xekc** [comment]
Can't reproduce it, I think it's fixed.
