### ISSUE TITLE
Unable to add location and school tags to post

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#176]
Create a post and click to add location (and school) tag. Enter tag name and click on "Add" button. Notice that location (and school) tag can not add to post.

Current code allows adding tags only from the suggestion drop-down. Using "Add" button is broken - even if I enter "Taipei" in the location tag field - I will not be able to add that (even though we have a location tag named "Taipei" in the database).

We need to improve this - pressing "Add" button has to work if the location / school with that name is in the database.

**Comment by indeyets** [comment]
plus! 0.5/0.5

**Comment by xekc** [comment]
@oopscurity please take this.

**Comment by Oopscurity** [comment]
@xekc accepted

**Comment by Oopscurity** [comment]
@dmitryvdovin Need API to check the existing of submitted school or location in the database.

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 0.01/0

**Comment by voidxnull** [comment]
plus! 0.33/0.33 Added the API methods.

**Comment by Oopscurity** [comment]
plus! 0.77/0

**Comment by Oopscurity** [comment]
@xekc Should input be case sensitive?

**Comment by Oopscurity** [comment]
plus! 0.53/0 done

**Comment by Oopscurity** [comment]
plus! 0.14/0 Implementation for post edit page

**Comment by Oopscurity** [comment]
plus! 0.3/0

**Comment by guiltypet** [comment]
Fixed.
