### ISSUE TITLE
Sorting different posts is not ordered by time at News Feed page

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#181]
Go to News Feed and notice that different posts are organized in random order by time

**Comment by indeyets** [comment]
plus! 0.35/0.35

**Comment by xekc** [comment]
Not a bug.

**Comment by xekc** [comment]
@ihork News feed is not sorted by created date, but rather any last interaction with the post "bumps" it up (or at least should bump it up). We'll need additional effort to make sure everything works as expected, but what we have here is expected - post creation date should not determine storing.
