### ISSUE TITLE
Size of navigation bar is changed to smaller when breadcrumb tags is displayed

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#184]
Click on any tag and notice that  breadcrumb tags displayed in navigation bar. Observe size of navigation bar. Click on first tag to open all tags and notice that size of bar is changed to smaller.

**Comment by indeyets** [comment]
plus! 0.77/0.77

**Comment by xekc** [comment]
@aleksijromanovskij please address this - nav bar has to be one size all the time

**Comment by indeyets** [comment]
plus! 2.25/2.25

**Comment by indeyets** [comment]
plus! 0.42/0.42

**Comment by indeyets** [comment]
Fixed. Size of navigation bar not changed when breadcrumb tags is displayed.  
Verified on Windows Pro 7/Chrome 49/FF45/Opera 35.
