### ISSUE TITLE
(1) Issue 187: Wrong time is displayed when create a new post

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#187]
Create a new post. Compare time in your control panel and time in just created post.

Might be connected to: https://trello.com/c/OrL8rs7q/380-issue-199-incorrect-date-and-time-displayed-in-header-for-all-school-tags-page

**Comment by indeyets** [comment]
plus! 0.27/0.27

**Comment by xekc** [comment]
@oopscurity please take this one

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 0.44/0 fixed

**Comment by Oopscurity** [comment]
plus! 0/-1.56

**Comment by indeyets** [comment]
plus! 0.47/0.47

**Comment by indeyets** [comment]
Fixed. Now the date and time are properly displayed in just created post.
Have checked on Windows Pro 7/Chrome 48/FF45/Opera 35, iPhone 6 /iOS 9.1, iPad Mini 2/iOS 8.3.
