### ISSUE TITLE
(2) Issue 189: School and location tags do not display in "I post to" section

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#189]
Add any location and school tag to post and publish this post. Scroll the page down to "I post to" section. Notice that only hashtags display in this section.

According to this card - https://trello.com/c/QRpYsz8p/194-8-i-post-to-8 all type of tags should display in "I post to" section

**Comment by indeyets** [comment]
plus! 0.6/0.6

**Comment by xekc** [comment]
@dmitryvdovin Please address this. All 3 kinds of tags should be visible here.

**Comment by Oopscurity** [comment]
plus! 0/4

**Comment by Oopscurity** [comment]
plus! 0.29/0

**Comment by Oopscurity** [comment]
plus! 0.21/0

**Comment by Oopscurity** [comment]
plus! 0.29/0

**Comment by Oopscurity** [comment]
plus! 0.46/0 Added schools and geotags to sidebar

**Comment by voidxnull** [comment]
plus! 0.5/0.5 Fixed `userTags` test.

**Comment by Oopscurity** [comment]
plus! 0.1/0

**Comment by guiltypet** [comment]
plus! 0.5/0.5

**Comment by guiltypet** [comment]
I can reproduce it (in case Hashtag was not posted before you post Location/School tags). Checked on Windows Pro 7/Chrome 49/FF45/Opera 35

**Comment by Oopscurity** [comment]
plus! 11/8.35

**Comment by Oopscurity** [comment]
plus! -11.1/-8.35

**Comment by Oopscurity** [comment]
plus! 0.8/0 Fixed this bug and the bug with likes (menu element wasn't displayed if user liked any tag page)

**Comment by guiltypet** [comment]
All 3 tag types displays in "I post to".
