### ISSUE TITLE
Smoke Testing

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#190]
- Testing the site all items, bug hunting in case no items to be tested in Ready for QA list and investigation
- Functional site testing and bug reporting
- To report the time spent for testing of the site 
- Card should be pined in list Ready for QA

**Comment by indeyets** [comment]
https://trello.com/c/eMmjfTn4/379-unable-to-see-bottom-of-location-school-dropdown-list

**Comment by indeyets** [comment]
plus! 0.73/0.73

**Comment by indeyets** [comment]
https://trello.com/c/OrL8rs7q/380-incorrect-date-and-time-displayed-in-header-for-all-school-tags-page

**Comment by indeyets** [comment]
plus! 0.7/0.7

**Comment by indeyets** [comment]
https://trello.com/c/YxBzK21E/381-able-to-save-school-tag-without-a-name-by-editing-this-tag

**Comment by indeyets** [comment]
plus! 0.67/0.67

**Comment by indeyets** [comment]
plus! 1.75/1.75

**Comment by indeyets** [comment]
https://trello.com/c/IUoLGIDQ/402-save-changes-button-is-not-active-under-manage-followers-tab

**Comment by indeyets** [comment]
plus! 0.48/0.48

**Comment by indeyets** [comment]
https://trello.com/c/lhQlOaxA/403-issue-221-saved-successfully-message-does-not-disappear-automatically

**Comment by indeyets** [comment]
https://trello.com/c/pc65G06z/406-issue-224-log-out-button-does-not-work

**Comment by indeyets** [comment]
plus! 1.84/1.84

**Comment by indeyets** [comment]
https://trello.com/c/WYV2oAS3/407-user-is-unable-to-add-school-tag-location-tag-and-hashtag-to-your-post

**Comment by indeyets** [comment]
plus! 0.52/0.52

**Comment by indeyets** [comment]
plus! 0.74/0.74

**Comment by indeyets** [comment]
https://trello.com/c/wl8jlhAk/414-issue-232-page-not-found-error-message-displayed-when-clicking-on-school-icon-at-school-tag-page

**Comment by indeyets** [comment]
https://trello.com/c/Rkp5siIQ/420-issue-238-thank-you-for-registering-message-is-dispalyed-after-logged-in

**Comment by indeyets** [comment]
https://trello.com/c/4owiqxYM/421-load-more-button-appears-even-when-there-s-no-post-to-show

**Comment by indeyets** [comment]
plus! 1.59/1.59

**Comment by indeyets** [comment]
https://trello.com/c/neyzrfrS/422-size-of-add-tags-to-your-post-pop-up-window-is-changed-when-switching-from-the-enter-manually-tab-to-used-recently-popular-tabs

**Comment by indeyets** [comment]
plus! 0.55/0.55

**Comment by guiltypet** [comment]
https://trello.com/c/mobHv0hi/452-issue-270-new-button-does-not-work-for-location-hashtag-and-school-tags

**Comment by guiltypet** [comment]
https://trello.com/c/RD3hGaeQ/453-issue-271-user-is-redirected-to-the-cannot-read-property-lat-of-undefined-page-after-editing-the-school-tag-page

**Comment by guiltypet** [comment]
plus! 1.09/1.09

**Comment by guiltypet** [comment]
https://trello.com/c/Ckg4Dqz9/458-issue-276-people-to-follow-block-is-missing-on-mobile-devices

**Comment by guiltypet** [comment]
https://trello.com/c/aiKWHEvx/459-issue-277-manage-followers-noone-is-a-misspelling-of-the-word-no-one

**Comment by guiltypet** [comment]
https://trello.com/c/bmsSBYiD/460-issue-278-profile-settings-and-log-out-are-cut-off-on-people-to-follow-page

**Comment by guiltypet** [comment]
plus! 1.24/1.24

**Comment by guiltypet** [comment]
https://trello.com/c/HNQVpcDU/474-crash-when-trying-to-save-post-after-editing-it

**Comment by guiltypet** [comment]
plus! 1.27/1.27

**Comment by guiltypet** [comment]
plus! 0.83/0.83

**Comment by guiltypet** [comment]
https://trello.com/c/1SsLLqNR/479-issue-297-link-icon-does-not-work

**Comment by guiltypet** [comment]
https://trello.com/c/FXYamHI8/482-issue-300-profile-name-is-not-highlighted-when-user-click-on-it

https://trello.com/c/U2Pn1q4O/483-issue-301-profile-name-from-menu-is-clickable-only-on-text-area

**Comment by guiltypet** [comment]
plus! 1.18/1.18

**Comment by guiltypet** [comment]
plus! 2.03/2.03

**Comment by guiltypet** [comment]
plus! 1.09/1.09

**Comment by guiltypet** [comment]
https://trello.com/c/p7fw4DWp/503-issue-320-the-amount-of-created-posts-is-not-shown-on-school-tag-page

**Comment by guiltypet** [comment]
https://trello.com/c/6ifKcrVd/518-issue-335-data-and-time-are-separated-by-username-in-post-at-right-side-of-page-when-username-is-long

https://trello.com/c/ANNmvlaG/519-issue-336-creation-date-and-time-is-displayed-only-at-school-tag-pages

https://trello.com/c/7cgtejwr/520-manage-followers-page-does-not-scroll-up-automatically-to-following-you-section-after-clicking-on-followers-at-profile-page

https://trello.com/c/4IPk0Mc5/522-issue-339-tags-which-were-liked-by-other-users-are-not-displayed-in-news-feed

**Comment by guiltypet** [comment]
https://trello.com/c/DH6yY3t3/531-issue-348-news-feed-page-is-overlapped-by-people-to-follow-section-on-ios
https://trello.com/c/4FpfQCWq/532-issue-349-posts-likes-favorites-tabs-are-cut-off-at-profile-page
https://trello.com/c/EZn1CuEw/534-no-post-is-not-displayed-on-school-location-hashtags-pages
https://trello.com/c/n2Cq7jPR/535-issue-352-alignment-of-text-is-incorrect-in-add-tag-to-your-post-pop-up

**Comment by guiltypet** [comment]
https://trello.com/c/CrTxzija/537-post-tags-overlaps-make-a-contribution-field-while-creating-a-new-post
https://trello.com/c/mwfzcTK5/538-add-tag-to-your-post-pop-up-is-not-scrollable
https://trello.com/c/Ol2CUi0X/539-location-and-school-icons-are-not-aligned-by-center

**Comment by guiltypet** [comment]
https://trello.com/c/smeCzW6r/542-suggestion-all-posts-should-be-sorted-by-date-of-last-update

**Comment by guiltypet** [comment]
https://trello.com/c/CSG6p8MX/546-side-menu-separates-from-navigation-bar-while-scrolling-news-feed-page

**Comment by guiltypet** [comment]
https://trello.com/c/ZZmCVI3V/556-issue-373-content-in-left-side-menu-is-not-static

**Comment by guiltypet** [comment]
https://trello.com/c/xPDxw8BC/560-issue-377-whole-page-is-cut-off-on-the-left-side

**Comment by guiltypet** [comment]
https://trello.com/c/7zOXgaQH/562-password-error-message-overlapped-by-x-mark-during-registering

**Comment by guiltypet** [comment]
https://trello.com/c/1cnLyTzH/580-ignore-button-has-no-border-and-background-color-on-ios-devices

**Comment by guiltypet** [comment]
https://trello.com/c/EHRtZ4Ia/581-issue-394-news-feed-user-is-able-to-create-duplicate-post-by-clicking-on-publish-button

**Comment by guiltypet** [comment]
https://trello.com/c/0teN5jiY/595-used-recently-tab-and-popular-tab-turns-back-to-enter-manually-tab

**Comment by guiltypet** [comment]
https://trello.com/c/A6cj6nY7/605-school-tag-cloud-overlaps-the-left-side-menu

**Comment by guiltypet** [comment]
https://trello.com/c/5OO6lewM/607-1-posts-is-displayed-instead-of-1-post-on-tag-s-page

**Comment by guiltypet** [comment]
https://trello.com/c/GMl7l20u/609-issue-418-tag-has-a-delay-to-disappear-after-deleting-published-post

**Comment by guiltypet** [comment]
https://trello.com/c/7FpMqFEE/613-issue-422-added-link-to-your-post-comes-out-of-the-post-on-the-right-side

**Comment by guiltypet** [comment]
https://trello.com/c/YcsLOGTf/614-issue-423-the-left-side-menu-is-overlapped-by-image-of-tags-page

**Comment by guiltypet** [comment]
https://trello.com/c/6cVulsC8/617-issue-426-404-page-not-found-after-moving-to-geotag-s-page

**Comment by guiltypet** [comment]
https://trello.com/c/dRdJ8oNw/619-issue-428-save-button-does-not-work-on-hashtag-location-tag-pages

**Comment by guiltypet** [comment]
https://trello.com/c/lMByqH0D/620-issue-429-edit-tab-is-available-on-tag-s-page-of-other-users

**Comment by guiltypet** [comment]
https://trello.com/c/tzBpPARm/621-add-button-does-not-appear-when-hover-over-each-tag-in-used-recently-tab

**Comment by guiltypet** [comment]
https://trello.com/c/EUuhx5wa/625-issue-434-tabs-posts-like-favorites-bio-are-cut-off-in-profiles-of-other-users-on-ios

**Comment by guiltypet** [comment]
https://trello.com/c/25Is4cdT/628-issue-437-click-here-link-does-not-work-in-email-notification

**Comment by guiltypet** [comment]
https://trello.com/c/2uyjXoMs/629-issue-438-change-email-frequency-in-your-account-settings-is-missing-in-email-notification

**Comment by guiltypet** [comment]
https://trello.com/c/B4q7peEr/630-email-basic-settings-page-not-available

**Comment by guiltypet** [comment]
https://trello.com/c/XFZJNKNE/632-issue-441-cannot-save-profile-picture-and-header-image-in-manage-followers-tab

**Comment by guiltypet** [comment]
https://trello.com/c/U6RwbHyd/633-user-s-name-and-count-of-followers-are-not-visible-when-uploaded-white-header-image#

**Comment by guiltypet** [comment]
https://trello.com/c/xXXPtwtK/638-cannot-logged-in-from-iphone-3gs

**Comment by guiltypet** [comment]
https://trello.com/c/sOWvWXll/639-issue-448-unable-to-save-updated-header-image-for-school-tag-page-and-hashtag-page

**Comment by guiltypet** [comment]
https://trello.com/c/DNzSFUwC/640-header-image-does-not-fully-displayed-in-preview-screen-on-mobile-devices

**Comment by guiltypet** [comment]
https://trello.com/c/qOBbEPx0/662-the-left-side-bar-is-overlapped-by-mapbox-link

**Comment by guiltypet** [comment]
https://trello.com/c/HaURn0CM/668-header-is-cut-off-on-the-user-s-profile-page#

**Comment by guiltypet** [comment]
https://trello.com/c/lnfa0AQQ/669-issue-477-error-when-move-to-related-post-with-link-attached

**Comment by guiltypet** [comment]
https://trello.com/c/V3J57diT/672-name-of-post-and-edit-buttons-displays-as-3-dots-at-school-geo-and-hashtag-page

**Comment by guiltypet** [comment]
https://trello.com/c/MshkXe17/673-incorrect-alignment-of-post-under-broken-video-link-on-mobile-devices

**Comment by guiltypet** [comment]
https://trello.com/c/CprW0oaA/675-blank-screen-displays-when-click-on-back-button-after-deleting-post#

**Comment by guiltypet** [comment]
https://trello.com/c/R7Uabzzc/676-issue-484-share-menu-is-cut-off-in-landscape-mode

**Comment by guiltypet** [comment]
https://trello.com/c/nQXBy2uQ/689-can-not-play-video-from-post-on-native-browser

**Comment by guiltypet** [comment]
https://trello.com/c/a0qv67QU/704-welcome-page-search-box-opens-when-click-on-login-button

**Comment by guiltypet** [comment]
https://trello.com/c/CVFFIkR9/709-issue-516-total-number-of-post-does-not-decrease-on-geo-tag-cloud-page-when-delete-a-post-from-geo-tag-page

**Comment by guiltypet** [comment]
https://trello.com/c/D4icOMs4/710-issue-517-can-not-tap-on-preview-and-cancel-buttons-after-uploading-profile-picture-on-iphone

**Comment by guiltypet** [comment]
https://trello.com/c/ArlPE8mu/711-issue-518-error-when-trying-to-login-or-register-on-ie

**Comment by guiltypet** [comment]
https://trello.com/c/PCeC0gOP/713-issue-520-site-has-desktop-design-on-mobile-devices-with-ios-7-x-8-x

**Comment by guiltypet** [comment]
https://trello.com/c/55BYuEa5/716-issue-523-options-add-autocomplete-off-to-password-fields-for-firefox

**Comment by guiltypet** [comment]
https://trello.com/c/4KssE3kx/729-issue-535-welcome-page-terms-conditions-link-not-working

**Comment by guiltypet** [comment]
https://trello.com/c/rAEc4ATX/739-issue-544-removed-roles-appears-again-after-saving-changes-and-navigating-through-the-website

**Comment by guiltypet** [comment]
https://trello.com/c/SQ35bobD/740-text-entered-in-the-description-field-is-missing-after-saving-changes

**Comment by guiltypet** [comment]
https://trello.com/c/YLZ2QO0V/742-issue-547-old-password-is-incorrect-message-can-be-duplicated-as-many-times-as-many-times-user-clicks-on-save-changes-button

**Comment by guiltypet** [comment]
https://trello.com/c/jqpRgNDg/746-issue-551-page-is-not-properly-displayed-after-tapping-on-edit-icon

**Comment by guiltypet** [comment]
https://trello.com/c/phHJTdYG/751-issue-556-web-site-hangs-when-clicking-on-back-button

**Comment by guiltypet** [comment]
https://trello.com/c/frVagE2q/777-issue-581-suggestion-change-the-color-of-the-login-button

**Comment by xekc** [comment]
Moving away from this system, closing placeholder issue.
