### ISSUE TITLE
Cannot upload profile picture

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#192]
Go to my profile. Click on profile picture to change it and click on "Choose file" button. Select any photo. 
Notice that photo is not uploaded.

upd: http://alpha.libertysoil.org/settings  
env: Win7 Chrome 48/FF44

**Comment by indeyets** [comment]
plus! 0.66/0.66

**Comment by xekc** [comment]
@aleksijromanovskij please take this one. @ihork please provide environment details.

**Comment by indeyets** [comment]
http://alpha.libertysoil.org/settings  
env: Win7 Chrome 48/FF44

**Comment by Oopscurity** [comment]
plus! 0/3

**Comment by Oopscurity** [comment]
plus! 0.6/0

**Comment by Oopscurity** [comment]
plus! 0.25/0

**Comment by Oopscurity** [comment]
plus! 0.6/0

**Comment by Oopscurity** [comment]
plus! 0.1/0

**Comment by guiltypet** [comment]
Profile picture uploaded successfully.  Verified on Windows Pro 7/Chrome 50/FF45
