### ISSUE TITLE
Add states to geotags

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#193]

**Comment by voidxnull** [comment]
plus! 0/3

**Comment by voidxnull** [comment]
plus! 7.33/4.33

**Comment by indeyets** [comment]
I'm not sure that understood it correctly. For geotags should be added and displayed in breadcrumbs state in case of US (e.g. 
North America > United States > *California* > Valley Springs ) right ?
As I've tested it the state is NOT displayed there. (pls see attached file)
@dmitryvdovin Am I right ? or there something else to test? any information would be helpful.

**Comment by indeyets** [comment]
plus! 0.41/0.41

**Comment by voidxnull** [comment]
@ihork, @xekc It certainly is not deployed yet. It seems like we have a discrepancy in our workflow here: should I move cards into the "Ready for QA / Testing" list when they are finished?

**Comment by indeyets** [comment]
@dmitryvdovin  yes please, in that case I will know that it ready for testing and I can start my work :)

**Comment by voidxnull** [comment]
Now we wait for `npm run geonames` on server.

**Comment by guiltypet** [comment]
States are added to geotags. Verified on Win 7/Chrome 50. It works on both  alpha server and production server.
