### ISSUE TITLE
"Choose your user picture" text not visible in pop-up window unless highlighted

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#194]
http://alpha.libertysoil.org/settings
For all browsers and devices

Go to Profile Settings and click on Profile picture to change it. 
The text "Choose your user picture" is not visible on this pop-up window unless it is highlighted by selecting it with left mouse click and a sweeping motion of the mouse across the pop-up window.
Please refer to the screenshot attached.

**Comment by indeyets** [comment]
plus! 0.51/0.51

**Comment by xekc** [comment]
Won't fix (we'll need another approach here.
