### ISSUE TITLE
"X" icon appears in wrong place drop-down list of school and location tags

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#195]
Create a new post and click to add school or location tag. 
Enter one letter to open dropdown list. Select any school (location). 
Open dropdown list again and notice that "X" icon displays in wrong place.

**Comment by indeyets** [comment]
plus! 0.71/0.71

**Comment by xekc** [comment]
@aleksijromanovskij visual debugging - I assume that's yours to fix.

**Comment by indeyets** [comment]
Fixed.

**Comment by indeyets** [comment]
X icon is not displayed in a dropdown list of school and location tags.
Checked on Windows Pro 7/Chrome 49/FF45, iPad Mini 2/iOS 8.3

**Comment by indeyets** [comment]
plus! 0.17/0.17
