### ISSUE TITLE
Following/Followers counts disappear from the profile header when moving to Bio tab

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#197]
http://alpha.libertysoil.org/username//bio
For all devices and browsers

Navigate to Profile page and click on Bio tab. Notice that the Following/Followers counts disappear as soon as user moves to Bio tab.

Please see the attached screenshots.

**Comment by indeyets** [comment]
plus! 0.51/0.51

**Comment by xekc** [comment]
Won't fix. We'll be re-doing this very soon.
