### ISSUE TITLE
(0.5) Issue 200: Able to save School tag without a name by editing this tag

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#200]
1. Go to News Feed tab
2. Create a post with school tag and Publish it
3. Navigate to this school tag
4. Navigate to Edit tab
5. Leave the name field empty and save it

AR: A school tag icon is displayed without a name after editing it.
See attached video.

**Comment by xekc** [comment]
@aleksijromanovskij @dmitryvdovin please decide who would be better to approach this bug.

**Comment by indeyets** [comment]
plus!  -1d 2.21/2.21

**Comment by indeyets** [comment]
plus! 0.48/0.48

**Comment by indeyets** [comment]
I can still save it without a name.
Checked on Windows Pro 7/Chrome 49/FF45/Opera 35

**Comment by indeyets** [comment]
@ihork now this fix on alpha

**Comment by guiltypet** [comment]
Тест

**Comment by guiltypet** [comment]
Fixed. Now the user is unable to save School tag without a name by editing it. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35, iPhone 6 /iOS 9.1, Nexus 5/Android 6.0.1

**Comment by guiltypet** [comment]
plus! 0.29/0.29
