### ISSUE TITLE
model for Comments

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#202]
модель/миграция: `[id, post_id, author_id, text, created_at, updated_at]` внешний ключ на posts
----
Links:

Epic: https://trello.com/c/ZCFIIi9w/382-comments-development

Next task: https://trello.com/c/XtBtPhGS/384-created-at-asc-task2

**Comment by indeyets** [comment]
plus! 0/2

**Comment by indeyets** [comment]
plus! 0.75/0
