### ISSUE TITLE
API: list of comments (task2)

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#203]
API: `GET /post/{id}/comments` — сортировка по `created_at ASC`

----
Links:

Task1: https://trello.com/c/GkVpAEY5/383-model-for-comments

Epic: https://trello.com/c/ZCFIIi9w/382-comments-development

Next task: https://trello.com/c/IqMOs7pP/385-authentication-all-comments

**Comment by indeyets** [comment]
plus! 0/2
