### ISSUE TITLE
Implement methods in API client (task 7)

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#208]
реализовать в «клиенте» и в «triggers» методы для вышеперечисленных серверных endpoint
----
Links:

Previous task: https://trello.com/c/K8Bcbyd2/388-list-of-posts-add-comments

Epic: https://trello.com/c/ZCFIIi9w/382-issue-201-comments-development

Next task: https://trello.com/c/taImGTUB/390-redux-reducer

**Comment by xekc** [comment]
@indeyets please review if this one is still needed

**Comment by guiltypet** [comment]
Works well. Have checked on Windows Pro 7/Chrome 50 using API Client.
