### ISSUE TITLE
Redux: progress, comments (task 10)

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#211]
Redux: завести в редюсере `progress` ключ `comments`. выключать прогресс по обоим действиям. стартовать по «обычному» `UI__SET_PROGRESS` (обойдёмся пока без гранулярности с раздельным прогрессом по постам)

----

Previous task: https://trello.com/c/XweOJGIV/391-redux-action-creators

Epic: https://trello.com/c/ZCFIIi9w/382-issue-201-comments-development

Next task: https://trello.com/c/7mAXuaN6/393-redux-set-comments-task-11

**Comment by indeyets** [comment]
@indeyets сейчас нет такого редюсера

**Comment by xekc** [comment]
@indeyets please review- do we still need this task?
