### ISSUE TITLE
React: Display comments from Redux (task 12)

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#213]
Переписать компонент `post/comments` на использование данных из редюсера `comments`. Должен отображаться список комментариев отсортированный по дате создания. Новые снизу.

Удалить `src/scripts/disqus-thread.js`

Текст комментария отображается как простой текст. Никакой интерпретации тегов или переносов строк быть не должно

**Comment by xekc** [comment]
test
