### ISSUE TITLE
React: Comment posting form (task 14)

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#215]
Если пользователь авторизован, то под списком комментариев выводится textarea и кнопка "Add Comment". Нажатие кнопки вызывает триггер, который добавляет комментарий к посту.

В случае успеха список комментариев заменяется на новый, пришедший в ответе сервера

В случае ошибки, ошибка выводится рядом с формой, есть возможность попробовать отправить комментарий повторно

**Comment by indeyets** [comment]
plus! 4.06/4.06

**Comment by guiltypet** [comment]
Works well. Verified on the following environments: Windows Pro 7/Chrome 50, iPhone 6 /iOS 9.3.1, iPhone 5/iOS 8.3, Motorola Moto X (2nd Gen.)/Android 5.1.1 .
