### ISSUE TITLE
React: Edit comment (task 15)

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#217]
Если текущий пользователь является автором комментария, то рядом с текстом комментария отображается ссылка "Edit". Нажатие на неё превращает заменяет текст комментария на textarea и кнопку Save.

Нажатие на кнопку Save должно вызвать trigger отправляющий изменение комментария на сервер.

В случае успешного ответа сервера, режим редактирования выключается и список комментариев полностью обновляется из данных пришедших в ответе сервера.

В случае ошибки, текст ошибки выводится рядом с кнопкой Save. Есть возможность попробовать повторно сохранить правку.

**Comment by indeyets** [comment]
plus! 3.98/3.98

**Comment by indeyets** [comment]
Сейчас нет индикации ajax запроса на сохранение комментария.

**Comment by guiltypet** [comment]
It works. Verified on Win Pro 7/Chrome 50, Motorola Moto X (2nd Gen.)/Android 5.1.1, iPhone 5/iOS 8.3.
