### ISSUE TITLE
React: Delete comment (task 16)

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#218]
Если текущий пользователь является автором комментария, то рядом с текстом комментарий отображается ссылка "Delete". Нажатие на эту ссылку вызывает триггер, который отправляет на сервер комманду на удаление комментария.

В случае успешного удаления список комментариев полностью перезаписывается данными пришедшими в ответе сервера.

В случае ошибки, тексто ошибки выводится рядом со ссылкой "Delete"

**Comment by guiltypet** [comment]
Works as expected. Have checked on Win 7/Chrome 50/FF45/Opera 35, Nexus 5/Android 6.0.1, iPhone 6 /iOS 9.3.1
