### ISSUE TITLE
"Save changes" button is not active under Manage Followers tab

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#220]
http://alpha.libertysoil.org/settings/followers
For all devices and browsers

Go to Profile settings. Click on Manage Followers. Scroll the page fully downwards and notice that the "Save changes" button is present for Manage Followers tab. Clicking on it does nothing.
I think this button is unnecessary and could be removed.

See the attached screenshot

**Comment by Oopscurity** [comment]
plus! 0.37/0.37 The button has been removed

**Comment by Oopscurity** [comment]
plus! 0.5/0.5

**Comment by Oopscurity** [comment]
plus! 0.1/0.1 Done. If `onSave` prop isn't received, save button will not be rendered.

**Comment by guiltypet** [comment]
Fixed. "Save changes" button is not present under Manage Followers tab. 
Checked on Windows Pro 7/Chrome 49/FF45/Opera 35, iPhone 6 /iOS 9.1, iPad Mini 2/iOS 8.3

**Comment by guiltypet** [comment]
plus! 0.16/0.16
