### ISSUE TITLE
"Saved successfully" message does not disappear automatically

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#221]
http://alpha.libertysoil.org/settings
For all devices and browsers

Go to Basic info page. Scroll the page down. Click on "Save changes" button.
AR: "Saved successfully" message still displays on page even if move to other page and go back to Basic info page. If click several times on "Save changes" button,  several message will appear.

**Comment by Oopscurity** [comment]
plus! 0/0.5

**Comment by Oopscurity** [comment]
plus! 0.17/0 Fixed

**Comment by Oopscurity** [comment]
plus! 0/-0.33

**Comment by guiltypet** [comment]
Only one message will appear if click several times on "Save changes" button. But message is still displayed when move to other section and go back Basic info page.

**Comment by guiltypet** [comment]
Fixed. Checked on Windows Pro 7/Chrome 50/FF45/Opera 35, iPhone 6 /iOS 9.3.1. It works on alpha server.
