### ISSUE TITLE
User is unable to add School tag, Location tag and Hashtag to your post

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#225]
http://alpha.libertysoil.org
For all devices and browsers

Navigate to News Feed tab. Type any content in the post field and select any School tag, Hashtag or Location tag. Notice that tags cannot be added.

Please find the attached video

**Comment by xekc** [comment]
@indeyets seems to be a real issue on alpha

**Comment by Oopscurity** [comment]
plus! 0.31/0.31 already done

**Comment by Oopscurity** [comment]
This is the reason: https://trello.com/c/etlTtMDS/408-issue-226-bug-tabs-do-not-work-after-minification
Done (https://github.com/Lokiedu/libertysoil-site/pull/229) and now wait for server restart.

**Comment by indeyets** [comment]
plus! 0.26/0.26

**Comment by indeyets** [comment]
Fixed for all devices and browsers.
