### ISSUE TITLE
BUG: Tabs do not work after minification

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#226]
The code relies on dynamic reading of `displayname` property. the problem is, that uglifyjs obfuscates it in production build. You have to use something more reliable

**Comment by Oopscurity** [comment]
plus! 0.3/0.3 done

**Comment by indeyets** [comment]
Have checked on Windows 8.1 Pro FF/Chrome/IE latest tabs now displayed.

But there are issue with this modals with displaying Used recently tab and modal size when switching between tabs I will create separate cards for this issues, current issue fixed.

**Comment by indeyets** [comment]
plus! 0.31/0.31
