### ISSUE TITLE
"Page Not Found" error message displayed when clicking on school icon at school tag page

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#232]
http://alpha.libertysoil.org/s/Butterflies-India-NGO
For all browsers

Open any school tag page. Click on school icon under image.
AR: New page is opened and "Page Not Found" error message displayed

**Comment by Oopscurity** [comment]
plus! 0/1

**Comment by Oopscurity** [comment]
plus! 0.25/0 Fixed link to correct

**Comment by Oopscurity** [comment]
plus! 0/-0.75

**Comment by indeyets** [comment]
The issue is fixed. Error message not displayed after clicking on school icon at school tag page. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35

**Comment by indeyets** [comment]
plus! 0.27/0.27
