### ISSUE TITLE
(0.01/0.01) Issue 237: Likes for tags test-coverage.

### ISSUE THREAD

**Issue by RusAlex** [Lokiedu/libertysoil-site#237]
Part of https://trello.com/c/p9BLVF84/405-issue-223-tags-full-semantic-connectivity
Tag likes Checklist

**Comment by RusAlex** [comment]
plus! 1.25/1.25

**Comment by RusAlex** [comment]
plus! 3.16/3.16

**Comment by RusAlex** [comment]
plus! 0.01/0.01 test

**Comment by RusAlex** [comment]
plus! 1/1

**Comment by RusAlex** [comment]
plus! -1/-1

**Comment by RusAlex** [comment]
plus!  -4d 1/1

**Comment by guiltypet** [comment]
@rusalex if it fixed please move card to QA passed list. Thanks.
