### ISSUE TITLE
"Thank you for registering!" message is dispalyed after logged in

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#238]
http://alpha.libertysoil.org/induction
For all devices and browsers

1. Click the "Join" button to create new account
2. Fill out all mandatory fields and click "Sign Up"
3. Verify message in your email to proceed registration
4. Login to the LibertyІSoil > Log out
5. Login again

AR: "Thank you for registering!" message instead of "You are logged in. You can proceed to your feed" message is displayed after logged in second time.

**Comment by Oopscurity** [comment]
plus! 0/1

**Comment by Oopscurity** [comment]
plus! 1/0 Fixed

**Comment by indeyets** [comment]
plus! 0.42/0.42

**Comment by indeyets** [comment]
Fixed. Now proper message is displayed after logged in.
Have checked on Windows Pro 7/Chrome 49/FF45/Opera 35
