### ISSUE TITLE
Minor UX issue: "Load more" button appears even when there's no post to show.

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#239]
http://alpha.libertysoil.org/
For all devices and browsers

Navigate to News Feed tab. Make sure you do not have any posts there. Notice that the "Load more" button is displayed even if no posts exist.
Please see attached screenshot.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214153468619710)
┆Created By: Vlad

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 0.76/0 Fixed

**Comment by Oopscurity** [comment]
plus! 0/-1.24

**Comment by Oopscurity** [comment]
plus! 0.08/0.08 Don't hide after request error

**Comment by indeyets** [comment]
plus! 0.08/0.08

**Comment by indeyets** [comment]
plus! 0.56/0.56

**Comment by indeyets** [comment]
The "Load more" button is not displayed when there's no post to show. 
But starts flicker when moving between two tabs. 
@oopscurity Could you please have a look at it.

**Comment by Oopscurity** [comment]
@indeyets look at this. Is it allowed?

**Comment by guiltypet** [comment]
As we have discussed with @indeyets, this button appears as a spinner to check if posts exist. So in case there are no any published posts this button disappears.

**Comment by guiltypet** [comment]
The issue still reproduced on alpha server and production server. Video attached.

**Comment by indeyets** [comment]
Can not reproduce
