### ISSUE TITLE
Size of "Add tags to your post" pop-up window is changed when switching from the Enter manually tab to Used recently/Popular tabs

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#240]
http://alpha.libertysoil.org/
For all devices and browsers

Navigate to News Feed tab. Type any content in the post field and select any tag. Switch from the "Enter manually" tab to "Used recently" tab in pop-up window. Notice that the size of pop-up window is changed when switching from one tab to another.
Refer to the screenshot.

**Comment by xekc** [comment]
This is a core design issue, it can't be fixed this way - we need a responsive design done for this interface element that will show how this thing works. Won't fix.
