### ISSUE TITLE
Posts with all tags types not displayed in news feed and tags used in posts not appears in "I post to" sections

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#256]
http://alpha.libertysoil.org/
Published posts with all tags types not displayed in news feed (after refreshing) and tags used in posts not appears in "I post to" sections

Create new post and add tags of all types, as result tags that posted to  not displayed in I post sections and post disappears from news feed after page refreshing 

Applicable for all envs.

**Comment by guiltypet** [comment]
plus! 0.55/0.55

**Comment by guiltypet** [comment]
It works. All published posts are displayed in News Feed tab after refreshing the page. Verified on the following environments:
Windows 10/Chrome 49/FF45, iPhone 6 /iOS 9.1, iPad Mini 2/iOS 8.3, Nexus 4/Android 5.1.1
For "tags used in posts not appears in "I post to" sections" issue has already created a separate card https://trello.com/c/escpxgZQ/370-2-issue-189-school-and-location-tags-do-not-display-in-i-post-to-section
