### ISSUE TITLE
Used recently tags tab design (Used recently and Added  subsection should be available for this tab)

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#257]
For this tab should be available two subsections:
Used recently: with tags used by user from prev times
Added: with tags what was added manually from Enter Manually tab

**Comment by Oopscurity** [comment]
@indeyets Is this card still actual?

**Comment by indeyets** [comment]
@xekc  Could you please provide designes  for Used recently tab, for more information. thanks

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 1/0 Done

**Comment by guiltypet** [comment]
There are two subsections: Used recently and Added.
