### ISSUE TITLE
Tag page header - clean H1 tag

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#265]
Current code for header of the tag http://alpha.libertysoil.org/geo/Africa is:

<div class="page__caption" data-reactid=".16xy6gfivpc.1.2.1.0"><span data-reactid=".16xy6gfivpc.1.2.1.0.0">Africa</span><span data-reactid=".16xy6gfivpc.1.2.1.0.1"> </span><span class="page__caption_highlight" data-reactid=".16xy6gfivpc.1.2.1.0.2">Education</span></div>

Our goal is to make this page extremely seo friendly. 

To do that, we will need to re-code this element so that it is a clean H1 tag, with as little extra code, as possible.

This part of the page is not a "caption". It is a bold, huge, important, HEADER of the page. The most important text that defines the whole page. It has to be clearly identified in code as one.

**Comment by indeyets** [comment]
Title wrapped to `h1`:

`<header class="page__caption" data-reactid=".ukppqcl1q8.1.1.1.0">
<h1 data-reactid=".ukppqcl1q8.1.1.1.0.0">ABC-Montessori</h1>
</header>`

Remove `data-reactid` attributes is not possible in current react version.

**Comment by indeyets** [comment]
plus! 1.07/1.07

**Comment by guiltypet** [comment]
Fixed. Checked on Win 7/Chrome 50/FF 46.0.1
See the screenshot below
