### ISSUE TITLE
Edge-to-Edge on sub-768 resolution

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#266]
On resolution below 768 all tag page elements have to run edge to edge on screen, without any gaps on the left or on the right side. 

On mobile resolutions website has to deliver an experience of an app.

**Comment by guiltypet** [comment]
There is the gap when resolution is below 768 (from 768- to 480 px) . and stripes appears on the left and right sides of the screen.
Checked with Chrome50 and FireFox

It's not a blocker but it should be fixed according to card description.
