### ISSUE TITLE
"New" button does not work for Location, Hashtag and School tags

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#270]
http://alpha.libertysoil.org/s/Newschoolnu
For all devices and browsers

1. Go to News Feed tab. 
2. Create new post with adding any tag to your post and publish it. 
3. Click on tag to open a page. 
4. Click the "New" button

AR:  Nothing happens after clicking the "New" button
Note: According to this card https://trello.com/c/e8Q8GCKa/351-21-issue-170-geo-tag-page-redesign-client-side-code, the "New" button has to create a new post with a pre-filled current tag

**Comment by Oopscurity** [comment]
plus! 0/4

**Comment by Oopscurity** [comment]
plus! 0.9/0

**Comment by Oopscurity** [comment]
plus! 1.03/0 Partial support for hashtags

**Comment by Oopscurity** [comment]
plus! 0.7/0

**Comment by Oopscurity** [comment]
plus! 1.57/0.2 Implemented for hashtags

**Comment by Oopscurity** [comment]
plus! 0.2/0.2 Implemented for geotag page.

**Comment by Oopscurity** [comment]
plus! 2/2 Done for school page.

**Comment by guiltypet** [comment]
New post is opened after clicking on "New" button
