### ISSUE TITLE
User is redirected to the "Cannot read property 'lat' of undefined" page after editing the School tag page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#271]
http://alpha.libertysoil.org/s/iSkool/edit
For all devices and browsers
 
1. Go to News Feed tab
2. Create new post with adding School tag to your post and publish it
3. Click on tag to open a School tag page
4. Navigate to Edit tab and scroll the page fully downwards
5. Click the "Save" button without making any changes

AR: User is redirected to the "Cannot read property 'lat' of undefined" page after editing the School tag page

**Comment by xekc** [comment]
@ihork please re-confirm the issue is actual for alpha / production servers. Move to "Backlog" if issue is still present.

**Comment by guiltypet** [comment]
I cannot reproduce the issue on both alpha and production servers. After an edit is saved successfully. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35, iPad Mini 2/iOS 8.3, iPhone 6 /iOS 9.3.1.
