### ISSUE TITLE
(13) Issue 272: Map for geotag's page

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#272]
Geotag page should show a map instead of an image. We can reuse existing Mapbox API for this.

Minimal implementation should show area which includes area around specified geotag.

1. Cities are stored as dots in geonames, so that means: show square of at least 40 km around this dot.
2. Countries have `areainsqkm` property, which gives us a rough estimate of radius, but, alas, do not have coordinates. what can we do about it?
3. States (aka admin1) – ?

Locations which have strict coordinates (cities, and points-of-interest) should be clickable.

Anyway, realistic implementation needs to be able to work with several (many) geopoints at once, showing area which includes all of them plus some border-area.

**Comment by indeyets** [comment]
plus! 0/2

**Comment by voidxnull** [comment]
plus! 2/2 Done.

**Comment by voidxnull** [comment]
plus! 0/4

**Comment by voidxnull** [comment]
Now I need to add lat/lon to states, countries, and continents. And calculate the zoom level for each geo object.

**Comment by voidxnull** [comment]
plus! 8/4

**Comment by xekc** [comment]
@dmitryvdovin where are we with this task? what is your estimate for finalizing this? What is the realistic deadline for it to make a next release?

**Comment by voidxnull** [comment]
@xekc I've finally found the suitable data for countries and states (US, Mexico, UK and some others) and already modified the importer. Continents are in progress: I'll finish them today, most likely. I may need some time to test the importer. So, I'll probably finish it either today or tomorrow.

**Comment by xekc** [comment]
@indeyets @dmitryvdovin can we put an emphasis on this work making it into friday's release?

**Comment by xekc** [comment]
@dmitryvdovin do I understand it correct that when this work is finished - we will have 100% of geo tag pages with maps?

**Comment by xekc** [comment]
@dmitryvdovin let me know if we're on track to releasing this on friday

**Comment by voidxnull** [comment]
@xekc Yes, It seems like I'm going to finish it today.

**Comment by voidxnull** [comment]
A lot of admin divisions will not have lat/lon. I just couldn't find appropriate data. I found data only for US, Canada, Mexico, GB and some other countries.

**Comment by guiltypet** [comment]
didn't test whole destination and areas.. but for small sities in Ukraine maps appears.
