### ISSUE TITLE
Manage Followers - "Noone" is a misspelling of the word "No one"

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#277]
http://alpha.libertysoil.org/settings/followers
For all devices and browsers

Go to Profile Settings page. Navigate to Manage Followers tab and make sure that you don't have followers. Notice that "Noone follows you yet" is displayed.

**Comment by Oopscurity** [comment]
plus! 0.1/0.1 fixed

**Comment by guiltypet** [comment]
Now it look good.

**Comment by guiltypet** [comment]
plus! 0.51/0.51
