### ISSUE TITLE
"Profile settings" and "Log out" are cut off on People to follow page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#278]
http://alpha.libertysoil.org/suggestions
For all devices and browsers

Login to LibertySoil. Click on Profile dropdown and notice that dropdown menu is cut off.
See attached screenshot

**Comment by Oopscurity** [comment]
plus! 0.1/0.1

**Comment by guiltypet** [comment]
It looks good on desktop and android devices . But "Log out" is cut off a little bit on iOS devices. Please see attached screenshot.

**Comment by guiltypet** [comment]
"Log out" is still cut off on iOS devices.
