### ISSUE TITLE
Unmounted Breadcrumbs component calls setState() - warning

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#289]
```
Warning:
setState(...): Can only update a mounted or mounting component.
This usually means you called setState() on an unmounted component.
This is a no-op. Please check the code for the Breadcrumbs component.
```

**Comment by xekc** [comment]
@indeyets are we OK with warning fixes as cards/tasks in trello? what is your opinion on where's the threshold for separate tasks?

**Comment by xekc** [comment]
@oopscurity when you input tasks - please put a hint on implications in description - what is the impact of this issue?

**Comment by indeyets** [comment]
this is a coding issue. I think it is ok to have this even as a blocker. But, please, do not extrapolate this comment to all possible warnings :)

**Comment by xekc** [comment]
Moved to https://github.com/Lokiedu/libertysoil-site/wiki/Warnings-and-console-errors-noticed
