### ISSUE TITLE
Bug: "short_text" type for posts with any size

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#293]
Zero size posts (without any content at all) should not be possible.

Disable "post" and "save" button if there is no content to post or the content consists of spaces only.
______
Type of new post doesn't depend on its size (except 0 non-space length). It doesn't matter - the type of post will be `short_text`.

**Comment by Oopscurity** [comment]
It's impossible to create a post with zero size. This card reports that type of new post doesn't depend on its size (except 0 non-space length). It doesn't matter - the type of post will be `short_text`.

**Comment by Oopscurity** [comment]
https://github.com/Lokiedu/libertysoil-site/pull/529

**Comment by Oopscurity** [comment]
Migrated to `react-inform`. Reported an issue: https://github.com/theadam/react-inform/issues/12

**Comment by Oopscurity** [comment]
upd: https://github.com/theadam/react-inform/pull/13

**Comment by xekc** [comment]
@oopscurity please verify if this was launched or indicate a waiting PR for this card.

**Comment by Oopscurity** [comment]
@xekc Merged. Only waiting for deployment.
