### ISSUE TITLE
"Internal server error" appears in console log when click on comment icon just created post

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#304]
http://alpha.libertysoil.org/
Windows 7, Chrome 49

Go to News Feed. Click to create a new post.
Write some text and add any tag.
Publish this post. Click on Comment icon.
Observe console log.

AR:  URL address is changed after first click but nothing happens and  "Internal server error"  displays in console log

**Comment by guiltypet** [comment]
plus! 0.76/0.76

**Comment by indeyets** [comment]
Need push 'comments: 0' property to JSON on create post API call.

**Comment by xekc** [comment]
@dmitryvdovin could you take this one too?

**Comment by voidxnull** [comment]
plus! 0/2

**Comment by voidxnull** [comment]
I can't reproduce the error. See screen.webm.

**Comment by guiltypet** [comment]
No error occurs when click on comment icon after a post is published. Verified on both production server and alpha server on Windows Pro 7/Chrome 50/FF46/Opera 35
