### ISSUE TITLE
Extra posts in right side of page display only for post with all tag types

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#305]
http://alpha.libertysoil.org/
Windows 7, Chrome 49

Navigate to News Feed.
Click on Comment icon for post with one or two tags type. 
Notice that there are not any posts in right side of page.
Click on Comment icon for post with all tags type. 
Observe that posts are appears in right side of page.

**Comment by guiltypet** [comment]
plus! 0.79/0.79

**Comment by xekc** [comment]
This behaviour is expected.
