### ISSUE TITLE
"Cannot read property 'username' of undefined" page is opened after reloading comments page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#308]
http://alpha.libertysoil.org/
Windows 7, Chrome 49

Navigate to News Feed page. Click on comment icon for post with all tag types. Refresh the page. Sometimes it happens after first refreshing, but sometimes after more than two.
AR: "Cannot read property 'username' of undefined" page is opened

**Comment by guiltypet** [comment]
plus! 0.7/0.7

**Comment by xekc** [comment]
Can't reproduce, don't think it's a real thing anymore, archiving. @ihork if you can reproduce this - re-open it, please.
