### ISSUE TITLE
(5) Issue 309: Custom header image for user profile

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#309]
As a user, I want to personalize my profile in a similar way I do it on Facebook, Twitter, Google+ and other social networks - so that I clearly identify it as mine and feel it as my "home".

**Comment by xekc** [comment]
@oopscurity please post a short update on your progress here (ideally with screenshots / estimate updates)

**Comment by Oopscurity** [comment]
Since we'd like to have unified interfaces with both tag pages and user page, we should:

1. Refactor existing tag pages (now they're absolutely awful to deal with).
2. Make tag pages to be unified with the same public properties.
3. Make unified tag edit pages for them (it's necessary to get preview in future).
4. Almost fully remake existing interfaces of uploading and managing photos since they'll work with not only user avatars soon.
5. Create API for uploading and managing photos of different (tags pages, user page) types and assignment.

I expect it'll be done till weekends from my side. So I will need to get help with following API soon.

**Comment by xekc** [comment]
@oopscurity description that you've posted goes way beyond the limits of this task. 

this is a task "give users ability to change profile header background ASAP" and it has to focus on the user. 

your list (1-2-3-4-5) is covering a much bigger scope than the initial task + it doesn't tell me where you are at the moment (no screenshots too). If you are doing a deep refactoring with what was supposed to be a smaller task - it is a problem + you've put quite some work into this task already. 

I'll put a meeting in today about it with @indeyets to make sure we're on the same page.

**Comment by Oopscurity** [comment]
@xekc Of course, I understand that the task is to provide users an opportunity to upload custom profile header picture. But you focus on reusing the code as much as possible and you *don't* want all these interfaces to develop separately. Besides, you want to develop new interface of uploading with possibility to see the preview of pictures.

So there is no way to develop this interface separately (and only) for uploading user profile header picture after all the requirements and goals in nearest future. Of course, if we wouldn't like to wriite hacks for all cases.

Tag pages. I've fully refactored them already. Now I'm focusing on interface of changing the photo (original task). So there'll not be additional difficulties with tags refactoring and the task'll be completed in time.

I'm able to discuss this task in the evening if it's necessary.

**Comment by xekc** [comment]
@oopscurity our goal is to have this feature in by the time release is due (this friday evening). do you think you can pull it through by then?

**Comment by xekc** [comment]
@oopscurity I need an update on our target delivery - do we expect this to be shipped on friday?

**Comment by Oopscurity** [comment]
@xekc Yes. I expect I'll have done it by Friday evening.

**Comment by xekc** [comment]
@oopscurity I'm in the total dark in terms of how exactly this will be implemented. If you roll this out and it has critical issues with implementation (UX design etc) - we won't have much time for fixes. If possible, provide early screenshots so I can give feedback and involve @ihork early on.

**Comment by guiltypet** [comment]
black stripes appears after uploading and saving background picture.

**Comment by guiltypet** [comment]
Verified on Windows Pro 7/Chrome 50, iPhone 6 /iOS 9.3.1, iPad Mini 2/iOS 8.3, Nexus 4/Android 5.1.1. 

I have created separate cards related to this card:
https://trello.com/c/XFZJNKNE/632-issue-441-cannot-save-profile-picture-and-header-image-in-manage-followers-tab
https://trello.com/c/U6RwbHyd/633-issue-442-user-s-name-and-count-of-followers-are-not-visible-when-uploaded-white-header-image
https://trello.com/c/xXXPtwtK/638-issue-447-cannot-logged-in-from-iphone-3gs
https://trello.com/c/sOWvWXll/639-issue-448-unable-to-save-updated-header-image-for-school-tag-page-and-hashtag-page
https://trello.com/c/DNzSFUwC/640-issue-449-header-image-does-not-fully-displayed-in-preview-screen-on-mobile-devices
