### ISSUE TITLE
[enh] Only post author can see like/favorites counts

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#312]
Only post author has to be able to see counters for favorites and likes. Anonymous or registered user can only see icons, without number of likes or favorites.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146853946818)
┆Created By: Vlad

**Comment by Oopscurity** [comment]
@xekc Is it right that any user (and even anonym) may visit someone's page and see that user's likes and favourites? Are these two ideas independent from each other?

**Comment by xekc** [comment]
lost relevance, closing
