### ISSUE TITLE
All comments to all posts are visible on news feed and tag pages

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#313]
To comment, user should not need to go to a separate page. 

All comments to every post have to be visible in news feed or in the tag feed.

User should be able to add a new comment right in his news feed.

Blocked by: https://trello.com/c/lG2vc4gF/507-issue-324-add-post-comments-field-to-api-call-api-v1-posts

**Comment by xekc** [comment]
@aleksijromanovskij you seem to be unblocked with https://trello.com/c/lG2vc4gF/507-issue-324-add-post-comments-field-to-api-call-api-v1-posts done - can we expect the comments in news feeds to be shipped this friday?

**Comment by guiltypet** [comment]
Working for http://alpha.libertysoil.org. Verified with Safari and Chrome 50
