### ISSUE TITLE
Remove extra information in relevant posts

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#314]
In right sidebar there's way too much data - only post content and post author icon-name are needed. Remove datestamp too. Link all (post content, author userpicture, name) - to post page.

**Comment by guiltypet** [comment]
Extra information is removed from Related posts and only post content and post author icon-name are displayed. Have checked on iPhone 6 /iOS 9.3.1,  Windows Pro 7/Chrome 50, iPad Mini 2/iOS 8.3.
