### ISSUE TITLE
(0.33/0.33) Issue 316: Getting `inst.render is not a function` error when anonymous

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#316]
All components containing the `PanelToolbarArea` or `PanelToolbar` component occasionally throw the `inst.render is not a function` error. These components are stateless — that means you can't just return `false` from them. Return `<noscript />` instead.

**Comment by voidxnull** [comment]
plus! 0.33/0.33 Done.

**Comment by guiltypet** [comment]
I have checked it and "inst.render is not a function" error not occurs for anonymous users. Verified on Win 7/Chrome 50/FF 46.0.1
