### ISSUE TITLE
(1.82/-0.18) (0) Issue 324: Add 'post_comments' field to API call '/api/v1/posts'

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#324]
I assume we need this to display comments on the news feed / feed of posts by tag/criteria.

On news feed (list of posts) pages comments will be collapsed so that only 3 comments (2 from the top and one from the bottom) are visible. See attached image.

On one post page all comments are visible on page load.

Blocks: https://trello.com/c/FuMAMPHP/496-issue-313-all-comments-to-all-posts-are-visible-on-news-feed-and-tag-pages

**Comment by xekc** [comment]
@indeyets who can do this task?

**Comment by xekc** [comment]
сервер должен ко всем постам всегда прицеплять два первых и один последний комментарий.
кроме случая одного поста — там присылать все
реакт аналогично должен отображать 2 первых и один последний на листингах даже если в редуксе сохранён полный набор, пока пользователь не нажмёт «показать все». это можно хранить в state
количество комментариев по прежнему нужно хранить отдельно

если пользователь нажал «показать все» и в редуксе данные есть, то отобразить их нужно моментально (в фоне отправив запрос серверу чтобы догрузить новые, например)

**Comment by xekc** [comment]
plus! 0.15/0.15 test

**Comment by voidxnull** [comment]
Here's the PR: https://github.com/Lokiedu/libertysoil-site/pull/399. One thing I want to discuss: should the `subscriptions` controller fetch all comments for all posts or only 2 first and 1 last?

**Comment by voidxnull** [comment]
plus! 1/-1

**Comment by voidxnull** [comment]
plus! 0.67/0.67

**Comment by guiltypet** [comment]
Working for both alpha server and production server. Verified on Win 7/Chrome 50/FF 46.0.1
