### ISSUE TITLE
Welcome page update, quotes section re-work

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#326]
Re-work of the quotes block in the footer.

**Comment by xekc** [comment]
@oopscurity please attach a screenshot of the end result - I don't see it on alpha, how can it be ready for deployment? I don't know how result looks or works. @indeyets can we have it on alpha?

**Comment by guiltypet** [comment]
Last item from check list is passed, for small screen size checked with iPhone 3Gs and Sumsung Galaxy Ace
Please see attached screenshot.
