### ISSUE TITLE
"Manage Followers" page does not scroll down automatically to "Following you" section  after clicking on Followers at profile page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#337]
http://alpha.libertysoil.org/settings/followers
Windows 7, Chrome 49

Go to Profile page. 
Click on "Following" at right side of page. "People you follow" section is opened. 
Click on "Followers". 
AR: Page does not scroll down to "Following you" 

NOTE: It rather as suggestion to improve in the future, card is created to not leave this functionality without attention.

**Comment by xekc** [comment]
Won't fix.
