### ISSUE TITLE
News Feed page is overlapped by "People to follow" section on iOS

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#348]
http://alpha.libertysoil.org/
iPhone 5/iOS 8.3 (640 x 1136px), Safari

Log in with valid credential. Tap on "your feed" link to open News feed page. Notice that News Feed page is overlapped by "People to follow" section.

**Comment by indeyets** [comment]
Fixed here https://github.com/Lokiedu/libertysoil-site/pull/350

**Comment by guiltypet** [comment]
Fixed. Verified on iPhone 5/iOS 8.3, iPhone 6 /iOS 9.3.1
