### ISSUE TITLE
Posts, Likes, Favorites tabs are cut off at Profile page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#349]
http://alpha.libertysoil.org/user/qaker
iPhone 5,iOS 8.3 (640 x 1136px), Safari

Go to Profile page (or tap on Profile name, My Likes, My Favorite from slide menu)
Observe that all pages are clipped.

**Comment by indeyets** [comment]
Fixed here - https://github.com/Lokiedu/libertysoil-site/pull/350

**Comment by guiltypet** [comment]
Posts, Likes, Favorites tabs are displayed correctly on both on your own profile page and on other another's profile page. Verified on iPhone 5/iOS 8.3, iPhone 6 /iOS 9.3.1
