### ISSUE TITLE
(2) Issue 351: No post is not displayed on school/location/ hashtags pages

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#351]
http://alpha.libertysoil.org/tag/www
iPhone 5, iOS 8.3 (640 x 1136px), Safari

Go to school/location/ hashtags page. Notice that amount of posts is displays next to "New" button but any post is displayed on the page

**Comment by Oopscurity** [comment]
@ihork Could you describe the full situation with the bug? I don't find it as you can see in my screenshot.

**Comment by guiltypet** [comment]
@oopscurity Chrome device mode not the best aproach to test responsive on mobile devices, since it's just screen size not emulator.
I've used real mobile iOS devices and in this case no posts are displayed when navigatet do tag. 
Such screenshots are taken from mobile devices and to reproduce it you should use any iOS device.
Also please see attached video noitems.mov for more information how it looks (used safari responsive desing mode)

**Comment by guiltypet** [comment]
Fixed. Verified on iPhone 5/iOS 8.3, iPhone 6s /iOS 9.1
