### ISSUE TITLE
"Post tags" overlaps "Make a contribution..." field while creating a new post

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#354]
http://alpha.libertysoil.org/geo/El-Tor
iPhone 5, iOS 8.3 (640 x 1136px), Safari

Open any tag page.
Tap on "New" button to create a new post
Tap on "3 dots" button
Observe the page

**Comment by xekc** [comment]
Won't fix, needs a mobile-specific interface / approach.
