### ISSUE TITLE
"Add tag to your post" pop-up is not scrollable

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#355]
http://alpha.libertysoil.org/
iPhone 5, iOS 8.3 (640 x 1136px), Safari

Open "Add tag to your post" pop-up. Add 6 or more tags to post. Hide the keyboard. Notice that unable to tap on "Save" or "Cancel" buttons.

**Comment by xekc** [comment]
Won't fix, needs mobile version.
