### ISSUE TITLE
Location and school icons are not aligned by center

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#356]
http://alpha.libertysoil.org/geo
http://alpha.libertysoil.org/s
iPhone 6, iOS 9.1 (750 x 1334px), Safari

Go to location (school) tag cloud page. Observe location and school icon.

**Comment by indeyets** [comment]
Починил уже. Тут - https://github.com/Lokiedu/libertysoil-site/pull/350

**Comment by guiltypet** [comment]
Now Location and School icons are properly aligned. Checked on iPhone 6 /iOS 9.3.1
