### ISSUE TITLE
Mobile UI fixing

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#374]

**Comment by guiltypet** [comment]
I have checked it and there are some issues for wich I have created separate cards:

https://trello.com/c/qOBbEPx0/662-the-left-side-bar-is-overlapped-by-mapbox-link
https://trello.com/c/TZ9pNki7/540-issue-357-make-a-contribution-field-scrolls-up-when-start-creating-a-new-post
https://trello.com/c/1cnLyTzH/580-issue-393-ignore-button-has-no-border-and-background-color-on-ios-devices
https://trello.com/c/DNzSFUwC/640-issue-449-header-image-does-not-fully-displayed-in-preview-screen-on-mobile-devices
https://trello.com/c/n2Cq7jPR/535-issue-352-alignment-of-text-is-incorrect-in-add-tag-to-your-post-pop-up
https://trello.com/c/mwfzcTK5/538-issue-355-add-tag-to-your-post-pop-up-is-not-scrollable
Verified on iPhone 5/iOS 8.3, Motorola Moto X (2nd Gen.)/Android 5.1.1, iPhone 6 /iOS 9.3.1, Nexus 4/Android 5.1.1, iPhone 6s /iOS 9.1
