### ISSUE TITLE
Whole page is cut off on the left side

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#377]
http://alpha.libertysoil.org/auth
Env.: iPhone 6s iOS 9.1, iPhone 5 iOS 8.3, iPhone 5s iOS 9.0, iPad 2 mini iOS 8.3, iPhone 6 iOS 9.3.

Whole page is cut off on the left side when registering. Will be better if page has the same border as right side.

**Comment by indeyets** [comment]
Fixed. https://github.com/Lokiedu/libertysoil-site/pull/375

**Comment by guiltypet** [comment]
Mandatory fields not aligned with page border. Checked on iPhone 6 /iOS 9.3.1, iPhone 5/iOS 8.3. Please see the screenshots below.
