### ISSUE TITLE
reducing page width should not show sidebar if user has switched it off

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#385]
1. Open http://www.libertysoil.org/geo/Europe in wide browser.

2. Click on the logo to hide sidebar.

3. Reducing the width of the browser does not re-appear sidebar (correct).

4. Increasing the width of the browser DOES re-appear sidebar, even though I haven't asked for it and I have specifically turned it off. 

This should not happen. If user has turned the sidebar off - it should not re-appear due to user's manipulations with the browser window. Increasing or reducing browser window size should not make sidebar visible, if I have turned it off myself.

**Comment by guiltypet** [comment]
I can reproduce it. Side bar re-appears after increasing browser window size.

**Comment by xekc** [comment]
obsolete
