### ISSUE TITLE
(1) Issue 387: hide comment edit / delete commands under a dropdown menu

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#387]
Subj. 

Drop down menu is visible when you CLICK on a small gray dot (becomes blue on click / on hover).

Drop down menu does not disappear on mouse out. To close it you need to click the blue circle icon again or click anywhere else on the screen.

**Comment by guiltypet** [comment]
To open dropodown triangle should be clicked, to close dropdown need to click out the dropdown or click on triangle.  Verified
