### ISSUE TITLE
(0.5) Issue 388: comment textarea height - 2 lines of text

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#388]
1. Correct height of comment textarea - 2 lines of text.

2. Button text should say "Post" not "Add Comment"

**Comment by guiltypet** [comment]
2 lines of text is height of comment textarea and "Post" button is displayed. Checked on Win 7/Chrome 50, Samsung S4/Android 4.4.2, iPhone 5/iOS 8.3, iPhone 6s /iOS 9.1. Please see the screenshot below.
