### ISSUE TITLE
[bug] News Feed - User is able to create duplicate post by clicking on "Publish" button multiple times

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#394]
Issue occurs on production server and alpha server
Env. Windows Pro 7/Chrome 49/FF45/Opera 35

1. Go to News Feed
2. Enter some text in text field
3. Click on "Publish" button several times

ER: "Publish" button should not be active until the post is published
AR: "Publish" button is active when post is in publishing status. And user is able to create many posts by clicking on it multiple times.

Please see attached video for more information

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/185566971593148/185580101671020)

**Comment by Oopscurity** [comment]
The bug was fixed. The issue is obsolete.
