### ISSUE TITLE
(21) Issue 402: local search (sphinx)

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#402]

**Comment by xekc** [comment]
@aleksijromanovskij where are we with the client side code for this task? Can @romangetman have everything he needs for integration, or are you working on this? What's you ETA if you are?

**Comment by indeyets** [comment]
Now working on dropdown design & behaviour implementation.

**Comment by xekc** [comment]
@romangetman I need your update here on status and estimates. Is it realistic to expect a release of this feature this friday?

**Comment by romangetman** [comment]
@xekc code will most likely be ready, but I don't think I'll manage to figure out the infrastructure changes (new docker container)

**Comment by xekc** [comment]
@indeyets could you please try to detail on infrastructure changes that @romangetman has mentioned below? I'm trying to see if we have a lot of hidden work here.

**Comment by romangetman** [comment]
@xekc there shouldn't be any hidden work, I just don't if things will work out of the box, i.e updating dockerfile will be enough

**Comment by Oopscurity** [comment]
* (re)Implemented search methods
* added search trigger, actions and reducer
* Reimplemented Search component

**Comment by xekc** [comment]
тест комментария - куда он пойдёт-то?
