### ISSUE TITLE
research possible ready/open source, react-friendly solutions for cards-on-hover element

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#405]
Following https://trello.com/c/mc7CTvQD/328-issue-147-pop-up-pop-down-card-for-tags 

We need to research ready-made, mobile-friendly, react-friendly solutions that could be used as a basis for UXD for that element.

Proposed researched solution should be approved by @indeyets

**Comment by Oopscurity** [comment]
Keywords: popover, hovercard.

examples:
* https://github.com/littlebits/react-popover (prefer)
* https://github.com/terebentina/react-popover
* https://github.com/uxcore/uxcore-popover

**Comment by xekc** [comment]
https://github.com/littlebits/react-popover has strange animation, as if positioning is buggy. "nose" of the pop-out baloon is repositioning itself after it becomes visible - doesn't look good.

https://github.com/terebentina/react-popover - TOO SLOW

https://github.com/uxcore/uxcore-popover - couldn't find the demo, http://uxcore.github.io/uxcore/components/uxcore-popover/ url on github doesn't open for me (neither http://uxco.re/ ?)

**Comment by xekc** [comment]
Invalid, full re-approach needed.
