### ISSUE TITLE
(13) Issue 409: new comment notification email

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#409]
Each time user receives a comment to his post (authored by this user) - we need to send an email and notify him about it.

**Same template should be used** - design attached is for guidance only.

**Comment by guiltypet** [comment]
I'm closing card. Email notification of new comment works and I have created separate cards https://trello.com/c/25Is4cdT/628-issue-437-click-here-link-does-not-work-in-email-notification, https://trello.com/c/2uyjXoMs/629-issue-438-change-email-frequency-in-your-account-settings-is-missing-in-email-notification, https://trello.com/c/B4q7peEr/630-email-basic-settings-page-not-available
related to this card
