### ISSUE TITLE
(0.5) Issue 413: Wikipedia descriptions aggregation for geo tags

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#413]
We need short description for geo tags pages that would give a few most important lines of context for the user: what continent and country is that geography in, a line or two of description.

We hope there is an easy/cheap way to aggregate that information from Wikipedia and (importantly) link back to the source page. We need the cheap and quick solution to replace existing placeholder text.

**Comment by voidxnull** [comment]
I've found an easy way to get a wikidata entry for each geotag: use the Geonames ID (https://www.wikidata.org/wiki/Property:P1566) property.

**Comment by xekc** [comment]
@dmitryvdovin could you update this with an ETA? I see that you've found a way but I'm not sure how far off are we with it. I'm working on more tasks towards geographies currently.

**Comment by xekc** [comment]
@dmitryvdovin and please don't leave cards in "In Progress" column if you are not currently (at the moment) working on those. Thanks!

**Comment by voidxnull** [comment]
@xekc The method I described doesn't work so well: it takes hours to process all 150000 geotags. Now I'm trying to come up with a better way. I think I'll try to parse the wikidata dump or continue searching for a better API method. It may take 1-3 days.

**Comment by voidxnull** [comment]
Getting a lot of errors with the wikidata sparql API. Trying out different queries.

**Comment by guiltypet** [comment]
There is no short description of tag on geo tag page now
