### ISSUE TITLE
School Tag cloud overlaps the left side menu

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#414]
Issue does not occur on production server
http://alpha.libertysoil.org/s
Windows Pro 7/Chrome 50/FF45/Opera 35

1. Login to Libertysoil
2. Navigate to News Feed
3. Create a post with School tag and publish it
4. Tap on this tag 
5. Tap on All schools icon

ER: School Tag cloud should not overlap the left side menu
AR: School Tag cloud overlaps the left side menu

Please see attached video

**Comment by voidxnull** [comment]
Can't reproduce. It seems like it was fixed.

**Comment by guiltypet** [comment]
Can not reproduce too. Fixed.
