### ISSUE TITLE
[bug] Added link to your post is outside of the post on the right side

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#422]
![2016-09-22 19-29-50-49y5j](https://cloud.githubusercontent.com/assets/1575753/18760936/f2c61460-80fa-11e6-9b65-5c3cd7e2ba83.png)
http://www.libertysoil.org/post/745dc971-19d9-45b9-866a-e001ed3ffbbb
http://www.libertysoil.org/post/063ec17d-2bd9-4b12-9f89-e8cc9f995a07
Windows Pro 7/Chrome 50/Opera 35
1. Navigate to News Feed tab
2. Click on Comment icon 
3. Notice that some added links to posts are outside of the post on the right side

AR: Added link to your post is autside of the post on the right side
ER: Link should displayed correctly.

Please see Screenshot attached

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146843735824)
┆Created By: Vlad

**Comment by xekc** [comment]
Seems fixed.
