### ISSUE TITLE
The left side menu is overlapped by image of tags page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#423]
Issue does not occur on production server
http://alpha.libertysoil.org/geo/Togo
For all devices and browsers

1. Create post, add any tag and publish it
2. Go to this tag

AR: The left side menu is overlapped by image of tags page 
Please see attached screenshot

**Comment by voidxnull** [comment]
I couldn't reproduce the issue.

**Comment by guiltypet** [comment]
Issue does not exist for now. Verified on alpha server and production server on Windows Pro 7/Chrome 52/FF47.0.1
