### ISSUE TITLE
"Save" button does not work on Hashtag/Location tag pages

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#428]
http://alpha.libertysoil.org/tag/coma/edit
http://alpha.libertysoil.org/geo/Gugunungan/edit
Windows Pro 7/Chrome 50/FF45/Opera 35

1. Go to News Feed
2. Create post, add  Hashtag and Location tag to your post and publish it
3. Click on published Hashtag or Location tag
4. Navigate to Edit tab
5. Click on "Save" button

Note: Edit tab is missing on Hashtag/Location tag pages on production server (Screenshot attached)

AR: Cannot save changes on Hashtag/Location tag pages
ER: Changes saved successfully

Please see video for more information

**Comment by Oopscurity** [comment]
Fixed in `feature/update-image` branch

**Comment by guiltypet** [comment]
for now Tag description is saved  verified on http://alpha.libertysoil.org/tag/somehash with Safari and Chrome 50
Can't check on production, since there is no edit button.
note: please see attached screenshot for more information.
