### ISSUE TITLE
Edit tab is available on tag's page of other users

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#429]
Issue does not occur on production server
http://alpha.libertysoil.org/s/SAIL-High-School/edit
For all devices and browsers

1. Login to Libertysoil
2. Navigate to other user's page
3. Click on any tag (Location/School/Hashtag) to open tag's page

AR: Edit tab is available on tag's page of other users
ER: Edit tab should not be available on tag pages of other users

Please find attached video

**Comment by Oopscurity** [comment]
I think it isn't a problem because

1. There's no idea of someone's tags in Libertysoil.
2. The idea of the project is collaboration.

Hovewer, We need to discuss it with @indeyets

**Comment by xekc** [comment]
@ihork this is not a bug. tags are not owned by anyone. anyone can edit any tag, just like on wikipedia anyone can edit any page.
