### ISSUE TITLE
[bug] Cannot save Profile picture and Header image in Manage Followers tab

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#441]
http://www.libertysoil.org/settings/followers
http://alpha.libertysoil.org/settings/followers
For all devices 
1. Login to Libertysoil with valid credentials
2. Go to Profile settings
3. Navigate to Manage Followers tab 
4. Change profile picture or header image

AR: User is unable to save their profile picture/header image in Manage Followers tab. The data will be lost if the user switches to another tab.
ER: Ability to save profile picture/header image in Manage Followers or not allow the user to change profile picture/header image in this tab.

Please see video for more information

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146854165052)
┆Created By: Vlad

**Comment by xekc** [comment]
@oopscurity please verify if this was launched or indicate a waiting PR for this card.

**Comment by Oopscurity** [comment]
@xekc Now there is no difference between settings tabs in saving the pictures (merged, waiting for deployment). But the tech of saving itself has been broken after migrate from `express` to `koa` (multipart). Needs PR.

**Comment by xekc** [comment]
@indeyets please give a few words of your opinion on how to proceed.

**Comment by indeyets** [comment]
works for me

**Comment by Oopscurity** [comment]
Fixed.
