### ISSUE TITLE
[bug] Unable to save updated header image for School tag page and Hashtag page

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#448]
Issue does not occur on production server
http://alpha.libertysoil.org/s/GramMangal/edit
For all devices and browsers
1. Go to Feeds tab
2. Type any content in the post field, add School tag or Hashtag to your post and publish it.
3. Click on this tag in published post
4. Navigate to Edit tab 
5. Change header image and save it

AR: User is unable to save their updated header image. "Bad Request" message is displayed.
ER: Updated header image should be saved successfully.

Please see video attachment

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146862618022)
┆Created By: Vlad

**Comment by Oopscurity** [comment]
There's no any error message displayed. Pictures can be uploaded successfully both at school and hashtag pages.
