### ISSUE TITLE
Header image does not fully displayed in Preview screen on mobile devices

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#449]
http://alpha.libertysoil.org/
http://www.libertysoil.org/
Mobile devices

1. Login to Libertysoil with valid credentials
2. Go to Profile settings
3. Tap on Upload icon and change profile background
4. Tap on the "Preview" button

AR: Header image does not fully displayed in Preview screen
ER: Header image should fully displayed as it was before previewing

Please see video for more information

**Comment by xekc** [comment]
obsolete
