### ISSUE TITLE
(1) Issue 451: Continents output

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#451]
All geo tags should be grouped in one of the following groups:

- Asia
- Africa
- North America
- South America
- Europe
- Australia

I assume that continents are hardcoded (not likely to change ever?), but not sure about it.

In this task we are talking server-side grouping of our output, client side / design work is expected to be carried over in https://trello.com/c/fNv5XViz/647-issue-456-mobile-first-layout-for-geo-page-no-data-just-vector-shapes-for-continents-and-everything-else-voidxnull-would-need card - **but this should not be a blocker** for this card.

**Comment by voidxnull** [comment]
On the server side, they are already grouped: each geotag has `continent_code` and `continent_id` columns.

**Comment by guiltypet** [comment]
There is one more continent - Antarctica which has not map image (see screenshot - geo page.png)

**Comment by voidxnull** [comment]
Added an image for Antarctica.
