### ISSUE TITLE
(5) Issue 452: Total number of tags per continent

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#452]
This is a task to get all the data ready for /geo/ (all location tags) page.

In https://trello.com/c/ZQkUU3HY/642-continents-output we have made sure all geo tags output is now grouped by continent.

In this task we will output the **total number of tags** per continent (as displayed in the picture). 

Number of non-empty tags (used by at least one post) should be displayed. If I  create new post, tag it with "New Jersey" - counter for North America should increase. If I delete this post or delete the tag for the post - counter should decrease accordingly.

**Comment by Oopscurity** [comment]
Implemented.

**Comment by guiltypet** [comment]
Now total number of tags per continent displays next to "New" and "Follow" button
