### ISSUE TITLE
Sorting within continents "by number of posts tagged with"

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#454]
The more posts are tagged with the tag - the higher tag is. 

Second sorting (for two tags with equal number of posts tagged with it) - alphabetical.

**Comment by voidxnull** [comment]
I think it'll be better to implement this as `tags.post_count` column which updates whenever the tag is attached (or detached) to a post.

**Comment by voidxnull** [comment]
I'm working on the caching of `post_count`.
