### ISSUE TITLE
Mobile first layout for /geo/ page (no data, just vector shapes for continents and everything else @voidxnull would need)

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#456]
Here we have a task to create static, mobile-first layout for /geo/ page.

It is relatively simple, but we don't have enough design materials to cover it fully. What we have here: https://trello.com/c/6PdYKhuc/598-issue-407-improve-location-tags-hub is a mobile layout 

We have a mobile screen with SVG shapes for continents and the desktop version should be secondary (developed later).

**Comment by voidxnull** [comment]
We need an svg for Antarctica.

**Comment by guiltypet** [comment]
Tags display in one line and are cut off at the Cloud tags page on iPhone 5/iOS 8.3.

**Comment by voidxnull** [comment]
Fixed.
