### ISSUE TITLE
Blank screen displays when click on Back button after deleting post

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#483]
http://www.libertysoil.org/
http://alpha.libertysoil.org/
All devices and browsers

Blank page is displayed when click on Browser back button after post is deleted

#Execution

**Test plan / how to demo:**
1. Go to News Feed 
2. Create a new post and publish it
3. Click on "Edit" button and delete this post
4. Click on Browser back button
5. Verify if blank page does not appear

**Comment by xekc** [comment]
Duplicate, closing
