### ISSUE TITLE
Cannot login (PC)

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#493]
1. Enter wrong password. Submit.
2. Enter the correct password and submit.
3. Login doesn't happen after any number of submitting the correct data. **Without error messages**

To login successfully user has to **refresh** web page.

**UPD:** It happens if page hasn't been loaded fully yet. Probably we shouldn't allow submit before render's finish.

**Comment by xekc** [comment]
@ihork please verify this.

**Comment by guiltypet** [comment]
Can not reproduce this. The user is successfully logged in after entering correct password.

**Comment by Oopscurity** [comment]
It happens if page hasn't been loaded fully yet. Probably we shouldn't allow submit before render's finish.

**Comment by guiltypet** [comment]
I can not reproduce it in these steps. After entering correct password the user is logged in. 
But I can not login with correct credentials or register at all in any IE browser. 
There is separate card for that: https://trello.com/c/ArlPE8mu/711-issue-518-error-when-trying-to-login-or-register-on-ie
