### ISSUE TITLE
[WIP] Refactorings

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#501]
Here I propose to discuss a few possible refactorings:
- [ ] Split the server into two parts: webpack-dev-server and the server itself. 
*It'll allow us to use nodemon to reload the server when code is changed.*
- [ ] Consider using https://github.com/erikras/ducks-modular-redux approach to organize our redux code. 
*The motivation for this change is pointed in the link.*

*... more to come*

**Comment by xekc** [comment]
https://docs.google.com/document/d/1wZXjq5b_C8Q6VUc4_r2Om-Wlg-up29C3PDpv3jGRirQ/edit
