### ISSUE TITLE
Move dev server out the main server

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#503]
It'll allow us to use nodemon to automatically reload server on code change. Potentially, It might solve the issue with the startup/reload time of the server.

**Comment by voidxnull** [comment]
It works now.

**Comment by voidxnull** [comment]
The PR needs an update. Furthermore, it'll be better to discuss the way it should be implemented more thoroughly.

**Comment by xekc** [comment]
Moved to https://github.com/Lokiedu/libertysoil-site/wiki/Technical-debt/
