### ISSUE TITLE
"Add tag" modal's hashtag suggest doesn't work

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#509]

**Comment by Oopscurity** [comment]
PR: https://github.com/Lokiedu/libertysoil-site/pull/510

**Comment by guiltypet** [comment]
"Add tag" modal's hashtag works properly. Have checked it on Windows Pro 7/Chrome 51/FF 47/Opera 35, iPhone 6 /iOS 9.3.1
