### ISSUE TITLE
Actions: naming

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#522]
After [separating the actions into multiple files](https://trello.com/c/ZCPsJJwX/660-issue-468-separate-actions-into-parts) I suggest to change the titles of some actions in order to simplify the code.
___
_Example_

**Before:**

```javascript
// declaration: src/actions/river.js
const CLEAR_RIVER = 'CLEAR_RIVER';

export function clearRiver() {
  return {
    type: CLEAR_RIVER
  };
}

// use
import * as a from '../actions';

a.river.clearRiver();
```

**After:**

```javascript
// declaration: src/actions/river.js
const CLEAR = 'RIVER__CLEAR';

export function clear() {
  return {
    type: CLEAR
  };
}

// use
import * as a from '../actions';

a.river.clear();
```

Note that action titles constants (strings) should be edited with BEM-like style to avoid ambiguity.

**Comment by xekc** [comment]
@indeyets please confirm

**Comment by xekc** [comment]
Moved to https://github.com/Lokiedu/libertysoil-site/wiki/Technical-debt/
