### ISSUE TITLE
Client-side development summary (oopscurity)

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#525]
This card's goal is to report all the time spent to development.

**Comment by Oopscurity** [comment]
[post/toolbar: react/jsx-no-bind fixes](https://github.com/Lokiedu/libertysoil-site/pull/526)

**Comment by Oopscurity** [comment]
[settings/followers: addUser action fix](https://github.com/Lokiedu/libertysoil-site/pull/527)

**Comment by Oopscurity** [comment]
[[WIP] PropTypes: project level](https://github.com/Lokiedu/libertysoil-site/pull/528):

* common;
* mesages;
* hashtags.

**Comment by Oopscurity** [comment]
[SideSuggestedUsers server rendering](https://trello.com/c/ZWUN5WMS/723-issue-530-sidesuggestedusers-server-rendering)

**Comment by Oopscurity** [comment]
[[WIP] PropTypes: project level](https://github.com/Lokiedu/libertysoil-site/pull/528):
* utils/createRequirableTypeChecker (also https://github.com/facebook/react/issues/7072)
* common/mapOf
* fixes, new refactorings
* GeotagPage tests

**Comment by Oopscurity** [comment]
https://github.com/Lokiedu/libertysoil-site/pull/534

**Comment by Oopscurity** [comment]
https://github.com/Lokiedu/libertysoil-site/pull/560

**Comment by xekc** [comment]
obsolete
