### ISSUE TITLE
Contacting us: Welcome page - Terms & Conditions link not working

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#535]
http://www.libertysoil.org/auth
http://alpha.libertysoil.org/auth
For all devices and browsers

This is registration process.
Clicking on Terms & Conditions link does nothing.

# Execution
**Test plan / how to demo:**
1. Go to http://alpha.libertysoil.org/auth
2. Click on "Join" button
3. Click on Terms & Conditions link - verify that Terms & Conditions page is opened

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146863425284)
┆Created By: Vlad

**Comment by voidxnull** [comment]
It seems like we don't have the "Terms and Conditions" page at all.
