### ISSUE TITLE
[bug] "Old password is incorrect" message can be duplicated as many times, as many times user clicks on  "Save changes" button

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#547]
http://www.libertysoil.org/settings/password
http://alpha.libertysoil.org/settings/password
Windows 7, Google Chrome 51

When I was changing  my password and entered incorrect current password, entered new password,  then click on "Save changes" button several times, I noticed that I can make  duplicates of the message "Old password is incorrect" as many times, as many times I click on "Save changes" button

# Execution
**Test plan / how to demo:**
1. Open "http://alpha.libertysoil.org/welcome" and log in with valid credentials
2. Go to "Change password" tab
3. Enter invalid current password
4. Enter new password and repeat it
5. Click on "Save changes" button several times
6. Verify if "Old password is incorrect" message appears only one time

Please see video for more information:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146871923476)
┆Created By: Vlad

**Comment by Oopscurity** [comment]
Fixed.
