### ISSUE TITLE
[bug] Page is not properly displayed after clicking on "Edit" icon

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#551]
http://alpha.libertysoil.org
http://www.libertysoil.org

Windows 7, Google Chrome 51

When I wanted to edit my post with lots of tags and clicked on "Edit" icon, I noticed that I was redirected to the page which was not properly displayed ("Save" and "Delete" buttons were almost invisible at the page)

#Execution

**Test plan / how to demo:**

Pre-condition: make sure you have a post with a lot of tags
1. Open http://alpha.libertysoil.org/welcome and log in with valid credentials
2. Go to "News Feed" page
3. Find a post with a lot of tags
4. Click on "Edit" icon
5. Verify if the user is redirected to the properly displayed page

Please see video for more information:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/185566971593148/185574195131583)

**Comment by indeyets** [comment]
works for me
