### ISSUE TITLE
[enh] Settings pages "Save" improvement

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#565]
Covers usability improvements and fixes related with Save button.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146873038590)
┆Created By: Vlad

**Comment by xekc** [comment]
@oopscurity please verify if this was launched or indicate a waiting PR for this card.

**Comment by Oopscurity** [comment]
@xekc it's ready for deployment. So PR has been merged but it hasn't been deployed to alpha yet.

**Comment by xekc** [comment]
@oopscurity a link to PR?

**Comment by Oopscurity** [comment]
@xekc https://github.com/Lokiedu/libertysoil-site/pull/573
