### ISSUE TITLE
Account: Password change move to /tools/

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#584]
![2016-09-22 20-58-02-w4aw9](https://cloud.githubusercontent.com/assets/1575753/18763924/44f0083e-8107-11e6-8219-9487a38edaf0.png)
Password change re-design, moving it out of the main website into tools > Account Settings.

Left-aligned templates.

Careful form design expected.
# Execution

**Definition of done:**

Password change displays in main website into tools > Account Settings

**Test plan (how to demo):**
1. Go to http://alpha.libertysoil.org/ and log in
2. Click on Account settings from left side menu - verify if there is Password change item
3. Click on Password change item - verify if page matches to the template

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/185566971593148/185573452495368)

**Comment by indeyets** [comment]
@xekc screenshot suggests, that we should store password-complexity data on server. I think that is a bad idea, as it would be a hint for malicious party, if such gets access to our database.

I suggest to analyse and show password complexity strictly before password is saved (for "New password" field). As soon as password is saved we shouldn't be able to know this data

**Comment by xekc** [comment]
@indeyets sorry, screenshot wasn't very thoughtful and I should have put that clearly. I was only doing visual work there, not much logic intended. Apart from having password complexity indication available for the user (to incentivise a more thoughtful account creation process) in general - I don't have any technical preferences here.
