### ISSUE TITLE
Upload images doesn't work

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#606]
An exception `i.getHeaders is not a function` comes from [`ApiClient.postMultipart()`](https://github.com/Lokiedu/libertysoil-site/blob/stable/src/api/client.js#L136)

The reason: `multipart` doesn't work after migration to `koa`.

**Comment by xekc** [comment]
@ihork please discuss with @oopscurity for any additional information and come up with a testing plan for this.

**Comment by indeyets** [comment]
Duplicate of #441
