### ISSUE TITLE
Schools: All school tags output

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#610]
**Definition of done:** a very basic skeleton-implementation of "Schools" tool launched. 
1. Output of a full list of **school tags** that have at least 1 post associated with them - on a /tools/schools page. 
2. School tags output sorted alphabetically A -> Z
3. Each tag is linked directly to the corresponding tag page (http://www.libertysoil.org/tag/School events 2016 etc).

**Acceptance criteria:**

It has to be simple and fully functional. Launched live. Design is not a blocker (can be launched without design), but any design work done will be appreciated.

**How to demo**
1. Open http://www.libertysoil.org/tools/schools/
2. See list of schools (school tags). Each tag is clickable. 

**Testing plan**

We want a very simple, even basic implementation that would work fast and reliably. We'll add features in small steps here. We'll want almost exactly same interfaces / features for other types of tags (hashtags, locations). Design / UX tasks are optional here (we'll have other cards where design will be a priority - but not now).

See also: https://trello.com/c/O7C2d1G0/814-issue-610-tools-schools-v-1

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146874404579)
┆Created By: Vlad

**Comment by xekc** [comment]
@ihork I drafted testing plan myself here - could you please review and improve it, if possible?

**Comment by xekc** [comment]
@indeyets can you do a code review here today?

**Comment by xekc** [comment]
According to this: https://github.com/Lokiedu/libertysoil-site/issues/610 all work here is done, but "how to demo" part of the card was ignored. The card is not done, until "how to demo" scenario can't be played successfully.

**Comment by voidxnull** [comment]
It works as described for me. I can see the list of school on http://www.libertysoil.org/tools/schools/. Did I miss something?

**Comment by xekc** [comment]
I consider this task done - more relevant improvements will follow shortly.
