### ISSUE TITLE
[enh] Any simple hack that will allow me to add "San Francisco (California)" geo tag to a post

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#615]
Currently we don't have a way to add this tag, because we have too many suggestions and there's no way to select one that is not on the initial list.

I need a hack. A quick interface change that would allow me (and any user, obviously) to select a tag that is 20th in the list of suggestions.

I don't know what is the good way to do it, but I'm open to anything reasonable. http://ui-patterns.com/patterns http://pttrns.com/ - anything fast enough is good for me.

**How to demo:**

1. Start a new post (while being logged in)

2. Type "San Francisco" 

3. **unknown**

4. Profit! I have added "San Francisco (California)" tag to the post successfully.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/185566971593148/185573463494267)

**Comment by indeyets** [comment]
Implemented via #628
