### ISSUE TITLE
store.current_user stores whole objects instead of ids 

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#617]
Following collections in the `current_user` store should be changed to store only ids/names/url_names of tags:
```
hashtags
geotags
schools
followed_hashtags
followed_schools
followed_geotags
liked_hashtags
liked_schools
liked_geotags
suggested_users
recent_tags:
  hashtags
  schools
  geotags
```
In the current state, all components depending on the collections listed above are prone to all kinds of synchronization bugs.

**Comment by xekc** [comment]
Moved to https://github.com/Lokiedu/libertysoil-site/wiki/Technical-debt/_edit
