### ISSUE TITLE
UX issue: "Follow" button is broken

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#641]
![2016-09-22 20-32-38-s30za](https://cloud.githubusercontent.com/assets/1575753/18763094/b8f236d4-8103-11e6-9292-ce55415f38c6.png)

http://www.libertysoil.org/suggestions

Clicking "Follow" button does nothing.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/207716452964842/207718723460621)

**Comment by indeyets** [comment]
It is broken EVERYWHERE, but fortunately it's only UI.
