### ISSUE TITLE
Engage: Add a new school tag

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#644]
**Acceptance criteria**
- User can add a new school, using all fields available in /edit interface for currently published school tags.
- New school tags become available throughout the site immediately. 
- Basic JS confirmation to warn user that tag name can't be edited (yet) and he has to get it right the first time ("After adding this tag you won't be able to edit school name anymore. Please be sure to get it right the first time, thanks!" Add school / Cancel  buttons - or something close to that)

**How to demo**
1. Open specific URL. If you aren't logged in, see basic 401 page (server returns 401 too)
2. Add school name (required), fill in other relevant (optional) fields.
3. Click "Add school", see JS warning, click "Add school"
4. See success message with a hyperlink to the school tag added. Link works, shows 0 posts.

### Definition of done
1. Schools can be added any time by any registered user of the site.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214147568581716)
┆Created By: Vlad

**Comment by indeyets** [comment]
@xekc should it be part of "tools" set of pages?

**Comment by xekc** [comment]
@indeyets "how to demo" fully answers this question. the answer is: I don't care. when "how to demo" is completed, school can be added. I don't care what the URL is - I just want the fastest turnaround of the task to user, in any shape of the UX.

**Comment by Oopscurity** [comment]
Related PR: https://github.com/Lokiedu/libertysoil-site/pull/695

**Comment by voidxnull** [comment]
@Oopscurity Already started working on this 3 days ago.

**Comment by xekc** [comment]
This issue was moved to Lokiedu/LS-Specification#79
