### ISSUE TITLE
People: basic contacts list 

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#645]
As a user, I want to see all people I interact with on LibertySoil.org in an address book -like interface, be able to follow / unfollow people easily.

Everything is about the same to our current way of handling it - we just move stuff to "Tools" section to improve features set there.

**Acceptance criteria**
- User can open "People" section in Toools
- All people you follow are listed. Button for "Follow" / "Unfollow" works.

**How to demo**
1. Log in LibertySoil.org, go to Tools
2. Open People, verify all people you follow are present. 
3. Clicking "Follow" (/ "Unfollow") button triggers your follow/unfollow status.

### Definition of done
User's followers / following management moved to Tools, all functionality is working.

## Could have
- [x] Mutual follows indication (highlight colour?)
- [x] User picture display
- [x] Bio display
- [x] Role display

![2016-09-22 20-42-31-ry8y0](https://cloud.githubusercontent.com/assets/1575753/18763391/19abd434-8105-11e6-9d6b-62d645b163ff.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146875637416)
┆Created By: Vlad

**Comment by indeyets** [comment]
@xekc What should happen (from the UI point of view) when user clicks "unfollow"?
for example: Should row disappear from the left menu?

**Comment by voidxnull** [comment]
**What's not done:**
- Mutual follows indication
- Role display

**Comment by xekc** [comment]
I consider this task done and will follow-up with further tasks shortly.
