### ISSUE TITLE
Handling exceptions throwed by methods of client API

### ISSUE THREAD

**Issue by Oopscurity** [Lokiedu/libertysoil-site#699]
Since https://github.com/Lokiedu/libertysoil-site/pull/680 `ApiClient`'s methods always throw exceptions after invalid requests.

Compatibility with some triggers has been broken. Error objects don't have custom structure now so it's incorrect to expect getting properties such as `e.response` or `e.response.body` of caught exceptions. We have to manipulate value of `e.message` only.

It's sometimes desirable (or even required) to fill responses' error fields in `ApiController` if they're empty.

Besides, we should check `fetchData` methods and other use cases of calling `ApiClient` to inspect possible problems related with migration.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214147599899079)
┆Created By: Vlad

**Comment by indeyets** [comment]
attn @RusAlex

**Comment by Oopscurity** [comment]
@RusAlex It may be useful: https://github.com/Lokiedu/libertysoil-site/tree/fix%2Fapi-client-exceptions

**Comment by RusAlex** [comment]
Yes I will go through controller code more close.

**Comment by RusAlex** [comment]
#700
