### ISSUE TITLE
agreed Errors thrown by client and caught by triggers 

### ISSUE THREAD

**Issue by RusAlex** [Lokiedu/libertysoil-site#705]
- [x] refactor triggers code to remove unusable code
- [x] refactor triggers to catch agreed Errors only

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146852289745)
┆Created By: Vlad

**Comment by xekc** [comment]
I'm closing this task, because it looks fully done - both checkboxes are filled and the other referenced issue is also closed. 

If more work is required here - please, put some time into describing it.

Thanks!
