### ISSUE TITLE
Geotag breadcrumbs are broken on alpha

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#710]
Example: http://alpha.libertysoil.org/geo/Europe

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/214146852134021)
┆Created By: Vlad

**Comment by xekc** [comment]
Only visible on alpha (production server works OK here?).

**Comment by voidxnull** [comment]
Yes, only alpha is affected.
