### ISSUE TITLE
Refactoring: Refactor schools table

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#728]
Before we get more school data, we have a chance to make the `schools` table more compatible with https://schema.org/EducationalOrganization.

## Currently, columns in the `schools` table map to the schema.org properties like this
| `schools` col | schema.org prop | |
|----|----|----|
| `name` | `name` | |
| `description` | `description` | |
| `lat` | `location.geo.latitude` | |
|` lon` | `location.geo.longitude` | |
| `principal_name` | `employee.givenName` | |
| `principal_surname` | `employee.familyName` | |
| `org_membership` | `memberOf[].name` | |
| `address` | `address.streetAddress` | |
| `city `| `address.addressCity` | |
| `postal_code` | `address.postalCode` | |
| `phone `| `telephone`, `address.telephone`  | |
| `website` | `url` | |
| `foundation_date` | `foundingDate` | |

## What we need to change
- [x] Replace `foundation_year`, `foundation_month`, and `foundation_day` with `founding_date` in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date format.

- [ ] Change the format of `org_membership` to an array of organization objects.

- [x] Merge `address1` and `address2` (and maybe `house`) into a single column. Two columns may be inconvenient for us because at least one provider (http://www.greatschools.org/) uses a single address field.

_WIP_

## What we might need to add
We don't have the data for this currently.

- [x] **`type` if it is important to distinguish between types**
A row in the `schools` table represents any educational organization, but it doesn't have a type. Here is the list of possible types:

CollegeOrUniversity
 ElementarySchool
 HighSchool
 MiddleSchool
 Preschool
 School

- [ ] **`legal_name` if needed**
- [ ] **`country`, `locality`, and `region` as string columns** for `address.addressCountry`, `address.addressLocality`, `address.addressRegion` schema.org props accordingly.
- [x] **`email`**
- [x] **`fax`**

**Comment by xekc** [comment]
We'll return to this in the near future in a comprehensive way covering remaining Schedma.org fields and going further into data fields used by WorldBank and UNICEF. I'll close this for now and will re-open as new issue.
