### ISSUE TITLE
Test Load More button on List page

### ISSUE THREAD

**Issue by RusAlex** [Lokiedu/libertysoil-site#729]
Test that button is visible for the required conditions. 

Related to the bug fixed in this commit:

https://github.com/Lokiedu/libertysoil-site/commit/f03647e87145771e05f8a44f9e8dfdab43ea9dec

**Comment by xekc** [comment]
@RusAlex RusAlex changed the pipeline from In Progress to Done on 21 Dec 2016 - I'll assume this was done, closing.
