### ISSUE TITLE
[WIP] Redux technical debt

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#735]
This issue contains a list of possible refactorings which will help to reduce the cost of further developing/maintenance.

- [x] Bring the format of action objects to [Flux Standard Action](https://github.com/acdlite/flux-standard-action). This will make it possible to process errors and 'not found' cases more easily since every FSA can represent an error. It will also allow us to create actions with less code using something like https://github.com/acdlite/redux-actions. 
**Issue: #738**

- [ ] ~~Replace triggers with async actions. I wrote down a list of reasons in #667.  I propose [redux-saga](https://github.com/redux-saga/redux-saga) as the most documented solution.~~

- [ ] Use [normalizr](https://github.com/paularmstrong/normalizr) to process nested models. Currently, we write a lot of code for this.
- [ ] ~~Consider organizing redux code into modules (https://github.com/erikras/ducks-modular-redux) to simplify the application structure. It might be worth reading [this](https://hackernoon.com/my-journey-toward-a-maintainable-project-structure-for-react-redux-b05dfd999b5#.yh29z2oxb).~~

WIP

**Comment by indeyets** [comment]
* FSA: yup, that's a good idea.
* redux-saga: no, sorry. NO. :). async actions, in general, complicate the dataflow and I'm slightly biased against them. I believe that usually we can get similar benefits by fine-tuning application architecture
* normalizr might be a way to go, but let's check alternatives before taking this step
* "ducks" are cool for simple projects, but really do not work for complex cases. Redux's approach is that same action can be handled by dozen of reducers and it is not exactly obvious where to put action definitions. and as soon as it is not obvious… "ducks" do not help us anymore

**Comment by RusAlex** [comment]
Also had some experience with redux-saga. 

There is alot of magic inside. And it's even easier to support our actions+triggers than always guessing and trying to realize what's going on inside sagas.

Also it's generator based and looks like step backward. Async/await is much more clean and understandable.

**Comment by indeyets** [comment]
(updated comment above)
