### ISSUE TITLE
Rough implementation for home page public posts timeline

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#742]
We need a rough version of the new home page implemented asap.

- [ ] New home page will have a title (h1) with the current date. 
- [ ] All best performing posts for that day are displayed without comments.
- [ ] We need to define and describe in wiki open simple formula for what "best posts" actually means.
- [ ] Some posts are displayed in the "full" view, some in the "short" view (narrow representation)

How to demo:

1. I open alpha.libertysoil.org
2. I see content that roughly follows https://docs.google.com/drawings/d/1HcmlzFtLZ7MbSbtMlIRH7C6KftQpMn8pvlVbOJqN-LE/edit
3. I see menu on the left side. I see current date's best posts, followed by yesterday's date best posts and so on.
4. There's infinite scroll + "load more" button that allows me to scroll ALL posts on Libertysoil if I choose to do so.

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;247288607794447">2017-01-16 14-48-24-cqzjz.png</a>

**Comment by artkravchenko** [comment]
@xekc Few questions:

1. Are posts with "full" view presented on mobile resolution or such posts are always in "short" view?
2. How to decide what posts display in "full" view and others - in "short" one?
3. How can I find yesterday's best posts? Is it related with infinite scroll?
4. "There's infinite scroll". Do I load only that day's posts this way? What if there's no more that day's unloaded posts? Do I see then identical view for day before (with best posts and so on) or just the list of older posts?
5. Where's avatar section in "full" post's view? Will this view replace current post's view or not?

**Comment by xekc** [comment]
➤ Vlad commented:
1. "full" view is one of the views, one of the ways to output post. both on mobile and on desktop resolutions post can be "short" or "full" or have some other presentation template. if post is displayed as "short" changing resolution should not change it's template - it will show as "short" on all resolutions.

2. server side decides that (algo to sort out most popular posts that day)

3. Scroll down, there will be yesterday, and all days since the start of the project if you scroll to the very end.

4. All posts on the site are loaded in, day by day. View for the day is the same (for now, later there will be some differences).

5. See attached picture. 

"Full" or "Short" don't replace current post view. It is a special presentation template for the home page - it does not have comments, it's lighter and is made for anon user / search engines.

**Comment by xekc** [comment]
@voidxnull implemented "all" that covers most of the needed value. I'll re-approach this task with design and further details, closing this version as obsolete.
