### ISSUE TITLE
Bug: Outdated info at the Favourites page

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#748]
How to test:

1. Go to your own account's Favourites page.
2. Unfav post.

* Even if there's no actually favoured posts, link to Favourites page doesn't disappear.
* Unfavoured post doesn't disappear from the feed.
* After moving to Likes page and coming back unfavoured post disappears but the link to Favourites page is preserved (even if the feed is empty).
* Full page's refresh or moving to other pages (except Likes page) update incorrect state.

This bug is also referenced here: [`user.js:46`](https://github.com/Lokiedu/libertysoil-site/blob/stable/src/pages/base/user.js#L46)

**Comment by xekc** [comment]
Insignificant bug - user journey for the moment when you have 0 favorites is very brief.
