### ISSUE TITLE
Text Template (Privacy Policy etc.) - first implementation

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#777]
We'll need a simple static arrangement to publish a few pages of text on behalf of the site. In this example it's "Privacy Policy" but right menu will contain a few more texts.

![2017-02-10 03-20-22-1daak](https://cloud.githubusercontent.com/assets/1575753/22812964/f4244c6a-ef3f-11e6-9961-50f9f7fbd285.png)

**Definition of done** 

1. I have a working hyperlink to http://alpha.libertysoil.org/website/privacy-policy page that looks similar to the given screenshot.
2. Menu on the left side works (expands, collapses) user's menu on the top right works, all site's code is latest, actual (it's not a copy that looks the same).
3. Any new text can be added within 15 minutes using the same template.
4. Menu on the right hand side can be modified to include a link to a new page - this link will be visible on all /website/ pages.

I expect at least:

/website/contact
/website/terms-of-service
/website/privacy-policy
/website/news
/website/about-us
/website/dmca

**Acceptance criteria**

- Text formatting in Privacy Policy body shouldn't attempt to mirror all the paddings and text style on the given picture. It is an example. 

- It should be possible to access content of those texts through our github (to improve and send pr).

- I don't think it makes sense to support Markdown at this point. We can add this later.

**Checklist**

- [ ] @indeyets confirmed technical architecture 
- [ ] it's clearly known how right menu will work - discussion needed with @xekc
- [ ] it's clear how we would do texts with images, youtube videos in them 
- [ ] metadata of the page (title, meta tags, h1 etc) is done well

**Comment by xekc** [comment]
@indeyets need your opinion - can I go with this task as is? Do we need any architectural perspective here? Should we aim for markdown support? Can we (how hard it is)? Green light this with a technical perspective on how we'll do it, please.

**Comment by indeyets** [comment]
I don't think markdown makes much sense. Markdown is good to have if we have a web-based editor and ability to add new pages.

As long as we do not try to make a CMS out of this I would stay with regular react-components. Simple html shouldn't be a problem. Metadata is tweakable via [Helmet](https://github.com/nfl/react-helmet).

**Comment by xekc** [comment]
This issue was moved to Lokiedu/LS-Specification#73
