### ISSUE TITLE
[wip] Human readable, informative post's slug

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#783]
Now posts' slugs aren't informative. The slugs will be displayed on posts with short-view so we most likely should add more readable and informative titles.

For example, the slug for https://alpha.libertysoil.org/post/411ea9f4-d09a-4456-b0dc-1134198fdafa
is `mr.Q Walker: New`

**Comment by xekc** [comment]
This issue was moved to Lokiedu/LS-Specification#44
