### ISSUE TITLE
Tag cloud server side

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#797]
We need server side support to be able to display tags in a cloud. 

We will use 3 sizes: normal, large, x-large. I don't have a good formula so I'm pulling this random way to create a tags cloud:

- Normal size has at least one entry.
- Large size is assigned with tags that have number of entries in the top 30% in this subset.
- x-Large size is assigned for top 5% tags by number of entries in this subset.

"In this subset" means that calculations have to be done separately for "United Kingdom" in Europe continent and in Global (/geo/) contexts - in one it could be the top 5% tag, in another it could be smaller. 

Hopefully once developed it could be customised. At this point I think it makes sense to have this data stored and calculated on the server size and then delivered through API so that client side can display the cloud with no delay, instantly.

The first usage of this data will happen on the /geo/Europe page (and other of the same type) where in addition to posts we'll display a cloud of tags:

![image](https://cloud.githubusercontent.com/assets/1575753/22946201/a6b8ea00-f2ee-11e6-85d0-260762a098ba.png)

**Comment by xekc** [comment]
Not sure if it makes sense to do it this way, @indeyets ?

**Comment by indeyets** [comment]
We won't know until we try. Can't really deduce it

**Comment by xekc** [comment]
This issue was moved to Lokiedu/LS-Specification#71
