### ISSUE TITLE
Bug: User page's title is incorrect if user hasn't set a full name

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#838]
The issue is related with the bug that `fullName` is equal to space character (` `) if user hasn't actually set his full name.

Extra spaces aren't visible due to renderer. There're 3 spaces between "of" and "on":
1. https://alpha.libertysoil.org/user/oopscurity - `Posts of   on LibertySoil.org`
2. https://alpha.libertysoil.org/user/oopscurity/likes - `Likes of   on LibertySoil.org`
3. https://alpha.libertysoil.org/user/oopscurity/favorites - `Favorites of   on LibertySoil.org`

The issue isn't present if user has full name. Compare:
* https://alpha.libertysoil.org/user/xekc - `Posts of Vladimiras Lekecinskas on LibertySoil.org`

Username or user's Name/ Surname needs to be added in title making it 'Posts of xekc on LibertySoil.org' for cases when fullName is not set.

**Comment by xekc** [comment]
@voidxnull дополни пожалуйста вывод в этом шаблоне таким образом, чтобы выводился юзернейм (он-то есть всегда) если fullName не указан.
