### ISSUE TITLE
Enhancement: Get rid of LWIP

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#842]
We need to replace all calls to LWIP with calls to GraphicsMagick. LWIP is practically not supported and will block our transition to NodeJS-8.x eventually (which will be next LTS-release and will happen quite soon now)

**Comment by xekc** [comment]
@voidxnull can you take on this one? 

How many places we have this at (I assume 3-4)? 

Can you give me an estimate? I assume it's 1-2 hours worth of work.

**Comment by voidxnull** [comment]
@xekc Ok. All the LWIP code is located in a single place. I think It'll take about 2-4 hours:
1) To figure out GraphicsMagick and how to replace LWIP with it.
2) To make sure nothing is broken afterwards.

**Comment by voidxnull** [comment]
@indeyets Have you considered using https://github.com/lovell/sharp instead of gm? It seems like it's the fastest solution out there and it doesn't require external dependencies.

**Comment by voidxnull** [comment]
On the other hand, gm doesn't depend on the node C/C++ addon API which may change between versions occasionally breaking our builds.

**Comment by indeyets** [comment]
Didn't know about this one. C++ api is not an issue. 
I care about project activity though.

Gm is a safe choice because of huge number of formats and active development. 

I will check sharp later
