### ISSUE TITLE
Suggest to follow in news feed

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#86]
Description given directly to @voidxnull - problem is that current users can't find enough people to follow (they don't log out and back in to see our suggestions) - this leads to them being unable to find new people.

Twitter-like solution is to display a few suggestions right in the sidebar, similar to our /suggestions page.

Three suggested users are required. Following a user changes status of the button to "Followed" - no other action happens. To get new suggestions user has to reload the page.

**Comment by voidxnull** [comment]
plus! 0/1.5

**Comment by voidxnull** [comment]
plus! 3/1.5

**Comment by voidxnull** [comment]
plus! 0.5/0.5

**Comment by voidxnull** [comment]
plus! -1/-1
