### ISSUE TITLE
Auth with third-party services

### ISSUE THREAD

**Issue by voidxnull** [Lokiedu/libertysoil-site#864]
- Facebook
- Google
- Twitter
- Github

**Comment by xekc** [comment]
@voidxnull update?

**Comment by voidxnull** [comment]
@xekc The back-end for both auto-fill and "Sign in with" is implemented for all 4 providers. "Sign in with" functionality if fully integrated into the new "Login" form. Later today I'm going to implement the profile picture loading for the "Sign in with" flow and auto-fill for the registration form. @Oopscurity may take the latter if he's not too busy.
