### ISSUE TITLE
Required posts order on a tag page - newest first

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#87]
Current posts order on http://www.libertysoil.org/s/Summerhill-School tag page is wrong - oldest post is first. 

Required posts order - newest first.

On the hashtags and on geo tags page logic is right: http://www.libertysoil.org/tag/democratic%20education (newest post is displayed first). Only school tags are affected.

**Comment by voidxnull** [comment]
plus! 0/0.33

**Comment by voidxnull** [comment]
plus! 0.5/0.17
