### ISSUE TITLE
Login, signup and password reset are impossible if JS is disabled

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#893]
Form submitting reloads the page without expected result.
Forms data isn't processed on the server-side.

Register form is unavailable, see #892.
To test the register form:
1. Load the page first (register form is displayed now) with JS enabled.
2. Disable JS.
3. Submit the form.

The submit still reloads the page. Registration isn't performed on the back end.

___
Attached screenshots:

![Login form](https://user-images.githubusercontent.com/12209129/30160700-cbb9e390-93f7-11e7-8c46-7088c2bdeb18.png)
![Register form](https://user-images.githubusercontent.com/12209129/30160687-bc25c372-93f7-11e7-8d85-e02b86f0a0a9.png)
![Password reset form](https://user-images.githubusercontent.com/12209129/30160708-d53b348c-93f7-11e7-9f52-21f3a4d5a6a9.png)

**Comment by indeyets** [comment]
@Oopscurity there should be an API method which registers user and responds with redirect. Redirect url should be configurable via post-parameter (but limited to our domain).

The form should use this API-method as form's `action=""`.

So, if user has JS enabled she proceeds with regular XHR-based flow.
But if user has JS disabled her browser falls back to "legacy" post+redirect flow.

**Comment by xekc** [comment]
➤ Vladimiras Lekecinskas commented:

Won't do
