### ISSUE TITLE
Language selector does not work on Safari

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#894]
Selector's options are not displayed after click on dropdown.
All Safari releases, including iOS-targeted ones, are affected.

Normal state:
![selector_normal](https://user-images.githubusercontent.com/12209129/30224259-3f1c0c54-94f8-11e7-9f39-b860c1467e6f.png)

Clicked state:
![selector_clicked](https://user-images.githubusercontent.com/12209129/30224258-3f13deb2-94f8-11e7-957e-4ae238c324d8.png)

**Comment by xekc** [comment]
➤ Vladimiras Lekecinskas commented:

Won't do (language selector design will be different).
