### ISSUE TITLE
"News Feed" link on /all may look like broken for anonymous user

### ISSUE THREAD

**Issue by artkravchenko** [Lokiedu/libertysoil-site#922]
When default page to redirect was `/welcome`, anonymous user was redirected if he tried to reach `/feed` page from `/all` and this transition was visible.

Now it looks like happening behind the scenes, because the user is redirected to `/all`, the page where he's already located, without any error message or login invitation.

Maybe, we should manage the redirection this way:
1. Open login modal with additional URL query parameter `?redir=`.
2. If user login succeeds, try to redirect the user to the page listed in `redir` parameter.
3. If the page doesn't exist, redirect to "Not found" page.
4. If user has declined the login invitation, keep him on the page he was located before the transition.

Besides, we probably shouldn't apply this behaviour to non existent pages and immediately redirect to "Not found" without opening the login modal.

**Comment by xekc** [comment]
Obsolete in light of #923
