### ISSUE TITLE
(1/1) Issue 93: Suggest to follow after login empty case

### ISSUE THREAD

**Issue by romagorbunov** [Lokiedu/libertysoil-site#93]
Following up https://trello.com/c/Vv2NdaEB/118-3-suggest-to-follow-after-login

We have a small flaw. 
If there are no suggestions, there should be no block for a user on that step, so the site must let user to News Feed directly straight away.

**Comment by indeyets** [comment]
plus! 0/2

**Comment by romagorbunov** [comment]
@romangetman Please, login time spent.

**Comment by indeyets** [comment]
plus! 1/1
