### ISSUE TITLE
"Login" changed to an icon #925

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#947]
This task extends #925

We need to change the "Login" text to an icon. The icon used in #925 is a part of a standard icons set in Axure and is temporary. We'll have a full change for all icons soon (hopefully).

At this point what we need is to make sure that:

* [x] "Log in" 60x60 box (full 60x60 are clickable, not only the icon) has fully replaced text version.
* [x] Properly annotated from an accessibility point of view (voice narration software will read "Log in" when this link is selected. You can select it while hitting "Tab" too.
* [x] Next to it there's a 60x60 "Search" block that shouldn't be in this task, but while you're at it..
* [ ] Background under those square buttons in sem-transparent. The level of transparency can be random in the range from 20% to 40% for solid white bg. This is an emulation for a system that will make consistent style elements out of animations similar to this one, we're doing "random opacity" as a temporary emulation.
* [x] Hover is "Log in" icon's opacity change from 90% to 100%
* [x] Login on top of an image looks close to what's pictured.

**Comment by artkravchenko** [comment]
@xekc,

> Background under those square buttons in sem-transparent. The level of transparency can be random in the range from 20% to 40% for solid white bg. This is an emulation for a system that will make consistent style elements out of animations similar to this one, we're doing "random opacity" as a temporary emulation.

Каждый последующий (справа налево к логотипу) активный блок в шапке менее прозрачен, чем предыдущий? Полупрозрачный вид стандартен для пунктов меню, т. е. не требует наведения мыши или клика? Или по умолчанию они все-таки непрозрачные белые?

1. no hover: fully white, no semi-transparency ![no hover: fully white, no semi-transparency](https://user-images.githubusercontent.com/12209129/32686063-e387dda4-c6d0-11e7-9425-282de2a1ba0e.png)
2. hover: semi-transparency relative to the background ![hover: semi-transparency relative to the background](https://user-images.githubusercontent.com/12209129/32686064-e3ac29d4-c6d0-11e7-9245-88f1288b826b.png)
3. hover + scroll: semi-transparency over the content under active block ![hover + scroll: semi-transparency over the content under active block](https://user-images.githubusercontent.com/12209129/32686065-e3d00ec6-c6d0-11e7-9082-2bc87ca7509e.png)

**Comment by artkravchenko** [comment]
@xekc, оцени, пожалуйста, корректность решения задачи.

Посмотри на комментарий выше https://github.com/Lokiedu/libertysoil-site/issues/947#issuecomment-343584074 или на текущее состояние шапки в https://alpha.libertysoil.org

Подобная ли прозрачность элементов шапки ожидается? Из представленных тобой скриншотов было не вполне понятно: настоящая прозрачность требуется или какие-либо оттенки серого.
