### ISSUE TITLE
"Logo with tags" reviewed #925

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#948]
"Logo with tags" currently does not work well #925

* [ ] If there are two or more tags in the breadcrumbs list - each should have a 60x60 shade under it with a random opacity to distinct every step in the breadcrumbs trail from the other. If it happens on white nav bar background - we use black solid fill with 2%-15% random opacity).
* [x] Logo doesn't feel right, but we'll be changing it to an SVG version soon. 
* [x] Newer version of tags (no line) has been used, I think it makes sense to try to implement this change in this task (change should be small?) - it's global for how tags look everywhere.
* [x] Each tag (starting with logo and on) is in it's 60 square center - except the last one that's full, has all text. 
* [x] Last tag in the header shouldn't be shortened  http://dipstudio.com/dev-i/2017-ax4g5.png

**Comment by artkravchenko** [comment]
@xekc,

> If there are two or more tags in the breadcrumbs list - each should have a 60x60 shade under it with a random opacity to distinct every step in the breadcrumbs trail from the other. If it happens on white nav bar background - we use black solid fill with 2%-15% random opacity).

Непрозрачность фона каждого последующего тэга в цепочке выше, чем у предыдущего, или абсолютно любая в пределах от 2% до 15%?
