### ISSUE TITLE
(#923) Label changes, hover fixes

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#952]
Extends #923

* [x] We'll need a manual toggl for open-close of the menu. For now it will be the 42x20px area to the right of the button with currently selected menu item (and thus colored in a specific color). 

When menu is open in this are there's same color vertical rounded rectangle. That's a switch. When menu is collapsed it's 4x4 circle. When it's open - it's as visible on the pictures.

* [x] Animation on scroll down changes.
  * [x] When user scrolls down menu shouldn't instantly auto-collapse into one 42px wide block. 
    * [x] While user is scrolling menu should be open. 
    * [x] When user has stopped scrolling, if his scrolling position is not on top of the page - then after 2 seconds of scroll inactivity menu collapses. 
    * [x] Only when the top is reached back - sidebar would extend itself automatically. If not it will remain collapsed until manually open. 
    * [x] If manually open it won't auto-collapse anymore.
* [x] Check behaviour on 42px
  * [ ] Each menu item has to light up with a different color when selected. On pictures here we only have blue and green, will provide remaining soon.
* [x] Check 120 px - that's not even done at all, possibly? 
* [x] Check 240 px - standard width
* [x] Check 340 px  - can't see that even on a very wide screen. Implemented?
* [x] Check mouse hovers to work as described in #923, show @xekc

**Comment by artkravchenko** [comment]
@xekc,
> - [ ] If manually open it won't auto-collapse anymore.

Is it applicable to anonymous users too?

**Comment by artkravchenko** [comment]
Scroll down animation improvement and support of manual toggl the automatic collapsing have been added in #955. Re-design of sidebar's navigation items including the mouse hover effects is covered with #956.
