### ISSUE TITLE
Babel6 #technicaldebt

### ISSUE THREAD

**Issue by romagorbunov** [Lokiedu/libertysoil-site#98]
Migrate to the new version of Babel transpiler. Currently, we use 5.x and want to switch to 6.x

The advantages are:

1. the possibility of fine-grained configuration, which would let us to get smaller, faster code
2. stricter checks, which would eliminate some error possibilities
3. better tooling (integration with modern code-transformation tools)

**Comment by voidxnull** [comment]
plus! 4/6

**Comment by voidxnull** [comment]
plus! 1.83/-0.17
