### ISSUE TITLE
Browserify -> WebPack2 #technicaldebt

### ISSUE THREAD

**Issue by romagorbunov** [Lokiedu/libertysoil-site#99]
We use a tool for transforming modular code to browser-friendly "bundles". Currently that is Browserify (driven by Gulp and Babelify). We want to migrate to Webpack2, which works faster, has better code-optimisation facilities and provides working hot-reload facilities.

**Comment by voidxnull** [comment]
plus! 6/10

**Comment by voidxnull** [comment]
plus! 4/0
